<?php

namespace Database\Seeders;

use App\Models\DashboardWidget;
use Illuminate\Database\Seeder;

class DashboardWidgetSeeder extends Seeder
{
    public function run(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Disable old / replaced widgets
        |--------------------------------------------------------------------------
        */
        DashboardWidget::whereIn('key', [
            'companyLine',
        ])->update([
                    'is_active' => false,
                ]);

        /*
        |--------------------------------------------------------------------------
        | Active dashboard widgets
        |--------------------------------------------------------------------------
        */
        $widgets = [
            /*
            |--------------------------------------------------------------------------
            | Global / Personal
            |--------------------------------------------------------------------------
            */
            [
                'key' => 'feed',
                'title' => 'Geburtstags-Feed',
                'subtitle' => 'Nächste Geburtstage',
                'icon' => 'cake',
                'color' => 'green',
                'default_view' => 'global',
                'tags' => ['today', 'hr', 'birthday'],
                'default_col_span' => 12,
                'default_row_span' => 1,
                'component' => 'dashboard.widgets.feed',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'clock',
                'title' => 'Uhrzeit',
                'subtitle' => 'Live Zeit & Datum',
                'icon' => 'clock',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['today', 'time'],
                'default_col_span' => 3,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.clock',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'hr',
                'title' => 'Zeiten & Abwesenheit',
                'subtitle' => 'Urlaub, Krankheit, Berufsschule',
                'icon' => 'calendar-days',
                'color' => 'green',
                'default_view' => 'personal',
                'tags' => ['hr', 'today'],
                'default_col_span' => 5,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.hr',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'absenceRequest',
                'title' => 'Abwesenheit beantragen',
                'subtitle' => 'Urlaub oder Krankheit melden',
                'icon' => 'calendar-plus',
                'color' => 'green',
                'default_view' => 'personal',
                'tags' => ['hr', 'absence', 'today'],
                'default_col_span' => 4,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.absence-request',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'key' => 'focus',
                'title' => 'Fokus Heute',
                'subtitle' => 'Aufgaben, Termine und offene Punkte',
                'icon' => 'target',
                'color' => 'danger',
                'default_view' => 'personal',
                'tags' => ['today', 'task', 'ticket', 'lead', 'angebot'],
                'default_col_span' => 4,
                'default_row_span' => 8,
                'component' => 'dashboard.widgets.focus',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'key' => 'myLiveInbox',
                'title' => 'Meine Live Aktivitäten',
                'subtitle' => 'Nur Aktivitäten, die mich betreffen',
                'icon' => 'radio',
                'color' => 'green',
                'default_view' => 'personal',
                'tags' => ['today', 'live', 'activity', 'task', 'appointment', 'lead', 'inquiry', 'offer', 'deal', 'ticket'],
                'default_col_span' => 5,
                'default_row_span' => 7,
                'component' => 'dashboard.widgets.my-live-inbox',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'key' => 'personalChart',
                'title' => 'Meine Arbeitsstunden',
                'subtitle' => 'Office / Montage pro Woche',
                'icon' => 'bar-chart-2',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['analytics', 'today'],
                'default_col_span' => 8,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.personal-chart',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'key' => 'notes',
                'title' => 'Meine Notizen',
                'subtitle' => 'Persönliche Notizen',
                'icon' => 'sticky-note',
                'color' => 'warning',
                'default_view' => 'personal',
                'tags' => ['today', 'notes'],
                'default_col_span' => 4,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.notes',
                'allow_multiple' => true,
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'key' => 'employeeCalendar',
                'title' => 'Mein Kalender',
                'subtitle' => 'Termine, Kunden, Tickets und Berichte',
                'icon' => 'calendar-days',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['today', 'calendar', 'appointments'],
                'default_col_span' => 8,
                'default_row_span' => 8,
                'component' => 'dashboard.widgets.employee-calendar',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'key' => 'shortcuts',
                'title' => 'Schnellzugriffe',
                'subtitle' => 'Häufige Aktionen',
                'icon' => 'zap',
                'color' => 'green',
                'default_view' => 'personal',
                'tags' => ['today', 'shortcuts'],
                'default_col_span' => 4,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.shortcuts',
                'allow_multiple' => true,
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'key' => 'miniChart',
                'title' => 'Mini Analytik',
                'subtitle' => 'Benutzerdefinierte Statistik',
                'icon' => 'line-chart',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['analytics'],
                'default_col_span' => 4,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.mini-chart',
                'allow_multiple' => true,
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'key' => 'empty',
                'title' => 'Leeres Widget',
                'subtitle' => 'Freier Platz für eigene Inhalte',
                'icon' => 'layout-template',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['custom'],
                'default_col_span' => 4,
                'default_row_span' => 3,
                'component' => 'dashboard.widgets.empty',
                'allow_multiple' => true,
                'is_active' => true,
                'sort_order' => 80,
            ],

            /*
            |--------------------------------------------------------------------------
            | Department cockpit
            |--------------------------------------------------------------------------
            */
            [
                'key' => 'deptOverview',
                'title' => 'Abteilungsübersicht',
                'subtitle' => 'KPIs der aktiven Abteilung',
                'icon' => 'building-2',
                'color' => 'blue',
                'default_view' => 'department',
                'tags' => ['department', 'analytics', 'team'],
                'default_col_span' => 12,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.dept-overview',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'key' => 'deptTeam',
                'title' => 'Team',
                'subtitle' => 'Mitarbeiter dieser Abteilung',
                'icon' => 'users',
                'color' => 'green',
                'default_view' => 'department',
                'tags' => ['department', 'team'],
                'default_col_span' => 4,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.dept-team',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 101,
            ],
            [
                'key' => 'deptCharts',
                'title' => 'Abteilungsanalyse',
                'subtitle' => 'Charts und Auswertung',
                'icon' => 'chart-no-axes-combined',
                'color' => 'blue',
                'default_view' => 'department',
                'tags' => ['department', 'analytics', 'charts'],
                'default_col_span' => 8,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.dept-charts',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 102,
            ],
            [
                'key' => 'deptRecent',
                'title' => 'Aktuelle Vorgänge',
                'subtitle' => 'Aktuelle Einträge der Abteilung',
                'icon' => 'list-checks',
                'color' => 'warning',
                'default_view' => 'department',
                'tags' => ['department', 'recent'],
                'default_col_span' => 6,
                'default_row_span' => 6,
                'component' => 'dashboard.widgets.dept-recent',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 103,
            ],
            [
                'key' => 'deptChanges',
                'title' => 'Letzte Änderungen',
                'subtitle' => 'Lead Activity Logs',
                'icon' => 'history',
                'color' => 'blue',
                'default_view' => 'department',
                'tags' => ['department', 'changes', 'activity'],
                'default_col_span' => 6,
                'default_row_span' => 6,
                'component' => 'dashboard.widgets.dept-changes',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 104,
            ],
            [
                'key' => 'deptPie',
                'title' => 'Projekt Status',
                'subtitle' => 'Auftrag, Lead, Montage, Angebot',
                'icon' => 'pie-chart',
                'color' => 'green',
                'default_view' => 'department',
                'tags' => ['department', 'analytics', 'sales'],
                'default_col_span' => 6,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.dept-pie',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 110,
            ],
            [
                'key' => 'deptBar',
                'title' => 'Umsatz nach Monat',
                'subtitle' => 'Monatliche Entwicklung',
                'icon' => 'bar-chart-3',
                'color' => 'warning',
                'default_view' => 'department',
                'tags' => ['department', 'analytics', 'sales'],
                'default_col_span' => 6,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.dept-bar',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 111,
            ],
            [
                'key' => 'deptHistory',
                'title' => 'Abteilungs-Historie',
                'subtitle' => 'Letzte Änderungen und Aktivitäten',
                'icon' => 'history',
                'color' => 'blue',
                'default_view' => 'department',
                'tags' => ['department', 'history', 'activity'],
                'default_col_span' => 12,
                'default_row_span' => 6,
                'component' => 'dashboard.widgets.dept-history',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 112,
            ],

            /*
            |--------------------------------------------------------------------------
            | Company cockpit
            |--------------------------------------------------------------------------
            | These are registered so saveDashboard() validation accepts them.
            | If you skip saving company view in JS, they still remain valid in registry.
            |--------------------------------------------------------------------------
            */
            [
                'key' => 'companyOverview',
                'title' => 'Unternehmens-Cockpit',
                'subtitle' => 'Unternehmensweite Übersicht',
                'icon' => 'building-2',
                'color' => 'green',
                'default_view' => 'company',
                'tags' => ['company', 'analytics', 'sales'],
                'default_col_span' => 12,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.company-overview',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 200,
            ],
            [
                'key' => 'companyMainArea',
                'title' => 'Mein Hauptbereich',
                'subtitle' => 'Main Bereich des aktuellen Mitarbeiters',
                'icon' => 'star',
                'color' => 'green',
                'default_view' => 'company',
                'tags' => ['company', 'department', 'main'],
                'default_col_span' => 4,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.company-main-area',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 201,
            ],
            [
                'key' => 'companyRevenue',
                'title' => 'Umsatz nach Monat',
                'subtitle' => 'Unternehmensweite Entwicklung',
                'icon' => 'bar-chart-3',
                'color' => 'warning',
                'default_view' => 'company',
                'tags' => ['company', 'analytics', 'sales'],
                'default_col_span' => 8,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.company-revenue',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 202,
            ],
            [
                'key' => 'companyTypes',
                'title' => 'Vorgänge nach Typ',
                'subtitle' => 'Leads, Angebote, Aufträge, Rechnungen',
                'icon' => 'pie-chart',
                'color' => 'blue',
                'default_view' => 'company',
                'tags' => ['company', 'analytics'],
                'default_col_span' => 6,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.company-types',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 203,
            ],
            [
                'key' => 'companyDepartmentPerformance',
                'title' => 'Bereiche im Vergleich',
                'subtitle' => 'Leads, Angebote und Aufträge pro Bereich',
                'icon' => 'chart-no-axes-combined',
                'color' => 'green',
                'default_view' => 'company',
                'tags' => ['company', 'departments', 'analytics'],
                'default_col_span' => 6,
                'default_row_span' => 5,
                'component' => 'dashboard.widgets.company-department-performance',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 204,
            ],
            [
                'key' => 'companyDepartmentList',
                'title' => 'Bereichsübersicht',
                'subtitle' => 'Team, Leads, Angebote und Aufträge',
                'icon' => 'list',
                'color' => 'blue',
                'default_view' => 'company',
                'tags' => ['company', 'department', 'list'],
                'default_col_span' => 6,
                'default_row_span' => 6,
                'component' => 'dashboard.widgets.company-department-list',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 205,
            ],
            [
                'key' => 'companyHistory',
                'title' => 'Unternehmens-Historie',
                'subtitle' => 'Letzte Aktivitäten im Unternehmen',
                'icon' => 'history',
                'color' => 'warning',
                'default_view' => 'company',
                'tags' => ['company', 'history', 'activity'],
                'default_col_span' => 6,
                'default_row_span' => 6,
                'component' => 'dashboard.widgets.company-history',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 206,
            ],

            [
                'key' => 'todayWeather',
                'title' => 'Wetter Heute',
                'subtitle' => 'Live Wetter an deinem aktuellen Standort',
                'icon' => 'cloud-sun',
                'color' => 'blue',
                'default_view' => 'personal',
                'tags' => ['today', 'weather'],
                'default_col_span' => 4,
                'default_row_span' => 4,
                'component' => 'dashboard.widgets.today-weather',
                'allow_multiple' => false,
                'is_active' => true,
                'sort_order' => 58,
            ],
        ];

        foreach ($widgets as $widget) {
            DashboardWidget::updateOrCreate(
                ['key' => $widget['key']],
                $widget
            );
        }
    }
}