/**
 * Hausplaner UI-3b — Werkzeug-Katalog aus dem 65-Tool-Paket (Yama), gefiltert auf CAD.
 * REINE Daten. DTP/Druck-Tools bewusst NICHT enthalten. Konsumiert von der Activation-Engine
 * (resolveToolState) wie TOOL_DEFINITIONS. Icons: /icons/<id>.svg (Assets folgen separat).
 */
import type { ToolDefinition } from './toolTypes';

export const TOOL_KATALOG: readonly ToolDefinition[] = [
  {"id": "selection", "label": "Auswahl", "icon": "/icons/selection.svg", "groupId": "auswahl", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte, Rahmen und Gruppen auswählen", "shortcut": "V", "meaning": "Objekte, Rahmen und Gruppen auswählen", "usageArea": "Allgemeine Objektbearbeitung", "group": "Auswahl", "tooltip": {"title": "Auswahl", "body": "Objekte, Rahmen und Gruppen auswählen", "usage": "Einsatzbereich: Allgemeine Objektbearbeitung", "shortcut": "V"}},
  {"id": "direct-selection", "label": "Direktauswahl", "icon": "/icons/direct-selection.svg", "groupId": "auswahl", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Ankerpunkte, Pfadsegmente oder Inhalte innerhalb eines Rahmens bearbeiten", "minSelectionCount": 1, "shortcut": "A", "meaning": "Ankerpunkte, Pfadsegmente oder Inhalte innerhalb eines Rahmens bearbeiten", "usageArea": "Pfad- und Detailbearbeitung", "group": "Auswahl", "tooltip": {"title": "Direktauswahl", "body": "Ankerpunkte, Pfadsegmente oder Inhalte innerhalb eines Rahmens bearbeiten", "usage": "Einsatzbereich: Pfad- und Detailbearbeitung", "shortcut": "A"}},
  {"id": "page", "label": "Seitenwerkzeug", "icon": "/icons/page.svg", "groupId": "layout", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Seitengröße und Seitenposition bearbeiten", "shortcut": "Shift+P", "meaning": "Seitengröße und Seitenposition bearbeiten", "usageArea": "Dokument- und Seitenlayout", "group": "Layout", "tooltip": {"title": "Seitenwerkzeug", "body": "Seitengröße und Seitenposition bearbeiten", "usage": "Einsatzbereich: Dokument- und Seitenlayout", "shortcut": "Shift+P"}},
  {"id": "gap", "label": "Lückenwerkzeug", "icon": "/icons/gap.svg", "groupId": "layout", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Abstände zwischen benachbarten Objekten verändern", "shortcut": "U", "meaning": "Abstände zwischen benachbarten Objekten verändern", "usageArea": "Layout und Verteilung", "group": "Layout", "tooltip": {"title": "Lückenwerkzeug", "body": "Abstände zwischen benachbarten Objekten verändern", "usage": "Einsatzbereich: Layout und Verteilung", "shortcut": "U"}},
  {"id": "type", "label": "Textwerkzeug", "icon": "/icons/type.svg", "groupId": "text", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Textrahmen erstellen und Text bearbeiten", "shortcut": "T", "meaning": "Textrahmen erstellen und Text bearbeiten", "usageArea": "Text und Beschriftung", "group": "Text", "tooltip": {"title": "Textwerkzeug", "body": "Textrahmen erstellen und Text bearbeiten", "usage": "Einsatzbereich: Text und Beschriftung", "shortcut": "T"}},
  {"id": "line", "label": "Linienwerkzeug", "icon": "/icons/line.svg", "groupId": "zeichnen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Gerade Linien zeichnen", "shortcut": "\\", "meaning": "Gerade Linien zeichnen", "usageArea": "Hilfslinien, Trennlinien und grafische Elemente", "group": "Zeichnen", "tooltip": {"title": "Linienwerkzeug", "body": "Gerade Linien zeichnen", "usage": "Einsatzbereich: Hilfslinien, Trennlinien und grafische Elemente", "shortcut": "\\"}},
  {"id": "pen", "label": "Zeichenstift", "icon": "/icons/pen.svg", "groupId": "zeichnen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Präzise Bézier-Pfade mit Ankerpunkten erstellen", "shortcut": "P", "meaning": "Präzise Bézier-Pfade mit Ankerpunkten erstellen", "usageArea": "Vektor- und Freiformgeometrie", "group": "Zeichnen", "tooltip": {"title": "Zeichenstift", "body": "Präzise Bézier-Pfade mit Ankerpunkten erstellen", "usage": "Einsatzbereich: Vektor- und Freiformgeometrie", "shortcut": "P"}},
  {"id": "add-anchor", "label": "Ankerpunkt hinzufügen", "icon": "/icons/add-anchor.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Zusätzliche Punkte in bestehende Pfade einfügen", "shortcut": "+", "meaning": "Zusätzliche Punkte in bestehende Pfade einfügen", "usageArea": "Pfadkorrektur", "group": "Pfad", "tooltip": {"title": "Ankerpunkt hinzufügen", "body": "Zusätzliche Punkte in bestehende Pfade einfügen", "usage": "Einsatzbereich: Pfadkorrektur", "shortcut": "+"}},
  {"id": "delete-anchor", "label": "Ankerpunkt löschen", "icon": "/icons/delete-anchor.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Punkte aus bestehenden Pfaden entfernen", "shortcut": "-", "meaning": "Punkte aus bestehenden Pfaden entfernen", "usageArea": "Pfadkorrektur", "group": "Pfad", "tooltip": {"title": "Ankerpunkt löschen", "body": "Punkte aus bestehenden Pfaden entfernen", "usage": "Einsatzbereich: Pfadkorrektur", "shortcut": "-"}},
  {"id": "convert-anchor", "label": "Ankerpunkt umwandeln", "icon": "/icons/convert-anchor.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Eckpunkte und Kurvenpunkte ineinander umwandeln", "shortcut": "Shift+C", "meaning": "Eckpunkte und Kurvenpunkte ineinander umwandeln", "usageArea": "Pfadkorrektur", "group": "Pfad", "tooltip": {"title": "Ankerpunkt umwandeln", "body": "Eckpunkte und Kurvenpunkte ineinander umwandeln", "usage": "Einsatzbereich: Pfadkorrektur", "shortcut": "Shift+C"}},
  {"id": "pencil", "label": "Bleistift", "icon": "/icons/pencil.svg", "groupId": "zeichnen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Freie Pfade zeichnen", "shortcut": "N", "meaning": "Freie Pfade zeichnen", "usageArea": "Skizzen und Freiformkonturen", "group": "Zeichnen", "tooltip": {"title": "Bleistift", "body": "Freie Pfade zeichnen", "usage": "Einsatzbereich: Skizzen und Freiformkonturen", "shortcut": "N"}},
  {"id": "smooth", "label": "Glätten", "icon": "/icons/smooth.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Unruhige Pfade glätten", "meaning": "Unruhige Pfade glätten", "usageArea": "Pfadnachbearbeitung", "group": "Pfad", "tooltip": {"title": "Glätten", "body": "Unruhige Pfade glätten", "usage": "Einsatzbereich: Pfadnachbearbeitung"}},
  {"id": "erase-path", "label": "Pfad löschen", "icon": "/icons/erase-path.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Teile eines freien Pfades entfernen", "meaning": "Teile eines freien Pfades entfernen", "usageArea": "Pfadnachbearbeitung", "group": "Pfad", "tooltip": {"title": "Pfad löschen", "body": "Teile eines freien Pfades entfernen", "usage": "Einsatzbereich: Pfadnachbearbeitung"}},
  {"id": "rectangle-frame", "label": "Rechteckrahmen", "icon": "/icons/rectangle-frame.svg", "groupId": "rahmen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Platzhalterrahmen für Bilder oder Inhalte erstellen", "shortcut": "F", "meaning": "Platzhalterrahmen für Bilder oder Inhalte erstellen", "usageArea": "Bild- und Inhaltsplatzierung", "group": "Rahmen", "tooltip": {"title": "Rechteckrahmen", "body": "Platzhalterrahmen für Bilder oder Inhalte erstellen", "usage": "Einsatzbereich: Bild- und Inhaltsplatzierung", "shortcut": "F"}},
  {"id": "ellipse-frame", "label": "Ellipsenrahmen", "icon": "/icons/ellipse-frame.svg", "groupId": "rahmen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Elliptischen Platzhalterrahmen erstellen", "shortcut": "F", "meaning": "Elliptischen Platzhalterrahmen erstellen", "usageArea": "Bild- und Inhaltsplatzierung", "group": "Rahmen", "tooltip": {"title": "Ellipsenrahmen", "body": "Elliptischen Platzhalterrahmen erstellen", "usage": "Einsatzbereich: Bild- und Inhaltsplatzierung", "shortcut": "F"}},
  {"id": "polygon-frame", "label": "Polygonrahmen", "icon": "/icons/polygon-frame.svg", "groupId": "rahmen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Polygonalen Platzhalterrahmen erstellen", "shortcut": "F", "meaning": "Polygonalen Platzhalterrahmen erstellen", "usageArea": "Bild- und Inhaltsplatzierung", "group": "Rahmen", "tooltip": {"title": "Polygonrahmen", "body": "Polygonalen Platzhalterrahmen erstellen", "usage": "Einsatzbereich: Bild- und Inhaltsplatzierung", "shortcut": "F"}},
  {"id": "rectangle", "label": "Rechteck", "icon": "/icons/rectangle.svg", "groupId": "formen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Rechteckige Grafikform erstellen", "shortcut": "M", "meaning": "Rechteckige Grafikform erstellen", "usageArea": "Formen und Flächen", "group": "Formen", "tooltip": {"title": "Rechteck", "body": "Rechteckige Grafikform erstellen", "usage": "Einsatzbereich: Formen und Flächen", "shortcut": "M"}},
  {"id": "ellipse", "label": "Ellipse", "icon": "/icons/ellipse.svg", "groupId": "formen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Kreis oder Ellipse erstellen", "shortcut": "L", "meaning": "Kreis oder Ellipse erstellen", "usageArea": "Formen und Flächen", "group": "Formen", "tooltip": {"title": "Ellipse", "body": "Kreis oder Ellipse erstellen", "usage": "Einsatzbereich: Formen und Flächen", "shortcut": "L"}},
  {"id": "polygon", "label": "Polygon", "icon": "/icons/polygon.svg", "groupId": "formen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrseitige Form erstellen", "meaning": "Mehrseitige Form erstellen", "usageArea": "Formen und Flächen", "group": "Formen", "tooltip": {"title": "Polygon", "body": "Mehrseitige Form erstellen", "usage": "Einsatzbereich: Formen und Flächen"}},
  {"id": "scissors", "label": "Schere", "icon": "/icons/scissors.svg", "groupId": "pfad", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Pfade an definierten Punkten auftrennen", "shortcut": "C", "meaning": "Pfade an definierten Punkten auftrennen", "usageArea": "Pfadbearbeitung", "group": "Pfad", "tooltip": {"title": "Schere", "body": "Pfade an definierten Punkten auftrennen", "usage": "Einsatzbereich: Pfadbearbeitung", "shortcut": "C"}},
  {"id": "free-transform", "label": "Freie Transformation", "icon": "/icons/free-transform.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte skalieren, drehen und scheren", "minSelectionCount": 1, "shortcut": "E", "meaning": "Objekte skalieren, drehen und scheren", "usageArea": "Transformation", "group": "Transformation", "tooltip": {"title": "Freie Transformation", "body": "Objekte skalieren, drehen und scheren", "usage": "Einsatzbereich: Transformation", "shortcut": "E"}},
  {"id": "rotate", "label": "Drehen", "icon": "/icons/rotate.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte um einen Referenzpunkt drehen", "minSelectionCount": 1, "shortcut": "R", "meaning": "Objekte um einen Referenzpunkt drehen", "usageArea": "Transformation", "group": "Transformation", "tooltip": {"title": "Drehen", "body": "Objekte um einen Referenzpunkt drehen", "usage": "Einsatzbereich: Transformation", "shortcut": "R"}},
  {"id": "scale", "label": "Skalieren", "icon": "/icons/scale.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objektgröße proportional oder frei verändern", "minSelectionCount": 1, "shortcut": "S", "meaning": "Objektgröße proportional oder frei verändern", "usageArea": "Transformation", "group": "Transformation", "tooltip": {"title": "Skalieren", "body": "Objektgröße proportional oder frei verändern", "usage": "Einsatzbereich: Transformation", "shortcut": "S"}},
  {"id": "shear", "label": "Scheren", "icon": "/icons/shear.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte schräg verzerren", "minSelectionCount": 1, "shortcut": "O", "meaning": "Objekte schräg verzerren", "usageArea": "Transformation", "group": "Transformation", "tooltip": {"title": "Scheren", "body": "Objekte schräg verzerren", "usage": "Einsatzbereich: Transformation", "shortcut": "O"}},
  {"id": "note", "label": "Notiz", "icon": "/icons/note.svg", "groupId": "review", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Interne redaktionelle Notiz einfügen", "meaning": "Interne redaktionelle Notiz einfügen", "usageArea": "Review und Zusammenarbeit", "group": "Review", "tooltip": {"title": "Notiz", "body": "Interne redaktionelle Notiz einfügen", "usage": "Einsatzbereich: Review und Zusammenarbeit"}},
  {"id": "eyedropper", "label": "Pipette", "icon": "/icons/eyedropper.svg", "groupId": "format", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Farbe oder Formatierung von einem Objekt übernehmen", "shortcut": "I", "meaning": "Farbe oder Formatierung von einem Objekt übernehmen", "usageArea": "Formatübertragung", "group": "Format", "tooltip": {"title": "Pipette", "body": "Farbe oder Formatierung von einem Objekt übernehmen", "usage": "Einsatzbereich: Formatübertragung", "shortcut": "I"}},
  {"id": "measure", "label": "Messen", "icon": "/icons/measure.svg", "groupId": "messen", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Abstände und Winkel auf der Arbeitsfläche messen", "shortcut": "K", "meaning": "Abstände und Winkel auf der Arbeitsfläche messen", "usageArea": "Kontrolle und Konstruktion", "group": "Messen", "tooltip": {"title": "Messen", "body": "Abstände und Winkel auf der Arbeitsfläche messen", "usage": "Einsatzbereich: Kontrolle und Konstruktion", "shortcut": "K"}},
  {"id": "hand", "label": "Hand", "icon": "/icons/hand.svg", "groupId": "navigation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Arbeitsfläche verschieben", "shortcut": "H", "meaning": "Arbeitsfläche verschieben", "usageArea": "Navigation", "group": "Navigation", "tooltip": {"title": "Hand", "body": "Arbeitsfläche verschieben", "usage": "Einsatzbereich: Navigation", "shortcut": "H"}},
  {"id": "zoom", "label": "Zoom", "icon": "/icons/zoom.svg", "groupId": "navigation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Ansicht vergrößern oder verkleinern", "shortcut": "Z", "meaning": "Ansicht vergrößern oder verkleinern", "usageArea": "Navigation", "group": "Navigation", "tooltip": {"title": "Zoom", "body": "Ansicht vergrößern oder verkleinern", "usage": "Einsatzbereich: Navigation", "shortcut": "Z"}},
  {"id": "fill", "label": "Fläche", "icon": "/icons/fill.svg", "groupId": "farbe", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Füllfarbe eines Objekts festlegen", "shortcut": "X", "meaning": "Füllfarbe eines Objekts festlegen", "usageArea": "Farbe und Oberfläche", "group": "Farbe", "tooltip": {"title": "Fläche", "body": "Füllfarbe eines Objekts festlegen", "usage": "Einsatzbereich: Farbe und Oberfläche", "shortcut": "X"}},
  {"id": "stroke", "label": "Kontur", "icon": "/icons/stroke.svg", "groupId": "farbe", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Konturfarbe und Linieneigenschaften festlegen", "shortcut": "X", "meaning": "Konturfarbe und Linieneigenschaften festlegen", "usageArea": "Farbe und Oberfläche", "group": "Farbe", "tooltip": {"title": "Kontur", "body": "Konturfarbe und Linieneigenschaften festlegen", "usage": "Einsatzbereich: Farbe und Oberfläche", "shortcut": "X"}},
  {"id": "swap-fill-stroke", "label": "Fläche/Kontur tauschen", "icon": "/icons/swap-fill-stroke.svg", "groupId": "farbe", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Füll- und Konturfarbe vertauschen", "shortcut": "Shift+X", "meaning": "Füll- und Konturfarbe vertauschen", "usageArea": "Farbe und Oberfläche", "group": "Farbe", "tooltip": {"title": "Fläche/Kontur tauschen", "body": "Füll- und Konturfarbe vertauschen", "usage": "Einsatzbereich: Farbe und Oberfläche", "shortcut": "Shift+X"}},
  {"id": "default-fill-stroke", "label": "Standardfarben", "icon": "/icons/default-fill-stroke.svg", "groupId": "farbe", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Fläche und Kontur auf Standardwerte zurücksetzen", "shortcut": "D", "meaning": "Fläche und Kontur auf Standardwerte zurücksetzen", "usageArea": "Farbe und Oberfläche", "group": "Farbe", "tooltip": {"title": "Standardfarben", "body": "Fläche und Kontur auf Standardwerte zurücksetzen", "usage": "Einsatzbereich: Farbe und Oberfläche", "shortcut": "D"}},
  {"id": "format-container", "label": "Container formatieren", "icon": "/icons/format-container.svg", "groupId": "format", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Formatierung auf Rahmen oder Objekt anwenden", "shortcut": "J", "meaning": "Formatierung auf Rahmen oder Objekt anwenden", "usageArea": "Formatsteuerung", "group": "Format", "tooltip": {"title": "Container formatieren", "body": "Formatierung auf Rahmen oder Objekt anwenden", "usage": "Einsatzbereich: Formatsteuerung", "shortcut": "J"}},
  {"id": "normal-screen", "label": "Normalansicht", "icon": "/icons/normal-screen.svg", "groupId": "ansicht", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Hilfslinien, Rahmen und nicht druckende Elemente anzeigen", "shortcut": "W", "meaning": "Hilfslinien, Rahmen und nicht druckende Elemente anzeigen", "usageArea": "Ansichtskontrolle", "group": "Ansicht", "tooltip": {"title": "Normalansicht", "body": "Hilfslinien, Rahmen und nicht druckende Elemente anzeigen", "usage": "Einsatzbereich: Ansichtskontrolle", "shortcut": "W"}},
  {"id": "preview-screen", "label": "Vorschauansicht", "icon": "/icons/preview-screen.svg", "groupId": "ansicht", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Dokument ohne Hilfslinien und Rahmen anzeigen", "shortcut": "W", "meaning": "Dokument ohne Hilfslinien und Rahmen anzeigen", "usageArea": "Präsentation und Kontrolle", "group": "Ansicht", "tooltip": {"title": "Vorschauansicht", "body": "Dokument ohne Hilfslinien und Rahmen anzeigen", "usage": "Einsatzbereich: Präsentation und Kontrolle", "shortcut": "W"}},
  {"id": "reference-point", "label": "Referenzpunkt", "icon": "/icons/reference-point.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Transformationsursprung innerhalb eines Objekts wählen", "meaning": "Transformationsursprung innerhalb eines Objekts wählen", "usageArea": "Präzise Transformation", "group": "Transformation", "tooltip": {"title": "Referenzpunkt", "body": "Transformationsursprung innerhalb eines Objekts wählen", "usage": "Einsatzbereich: Präzise Transformation"}},
  {"id": "link-proportions", "label": "Proportionen sperren", "icon": "/icons/link-proportions.svg", "groupId": "transformation", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Breite und Höhe gekoppelt ändern", "meaning": "Breite und Höhe gekoppelt ändern", "usageArea": "Präzise Transformation", "group": "Transformation", "tooltip": {"title": "Proportionen sperren", "body": "Breite und Höhe gekoppelt ändern", "usage": "Einsatzbereich: Präzise Transformation"}},
  {"id": "align-left", "label": "Links ausrichten", "icon": "/icons/align-left.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte an der linken Kante ausrichten", "minSelectionCount": 2, "meaning": "Mehrere Objekte an der linken Kante ausrichten", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Links ausrichten", "body": "Mehrere Objekte an der linken Kante ausrichten", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "align-center", "label": "Horizontal zentrieren", "icon": "/icons/align-center.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte horizontal zentrieren", "minSelectionCount": 2, "meaning": "Mehrere Objekte horizontal zentrieren", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Horizontal zentrieren", "body": "Mehrere Objekte horizontal zentrieren", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "align-right", "label": "Rechts ausrichten", "icon": "/icons/align-right.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte an der rechten Kante ausrichten", "minSelectionCount": 2, "meaning": "Mehrere Objekte an der rechten Kante ausrichten", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Rechts ausrichten", "body": "Mehrere Objekte an der rechten Kante ausrichten", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "align-top", "label": "Oben ausrichten", "icon": "/icons/align-top.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte an der oberen Kante ausrichten", "minSelectionCount": 2, "meaning": "Mehrere Objekte an der oberen Kante ausrichten", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Oben ausrichten", "body": "Mehrere Objekte an der oberen Kante ausrichten", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "align-middle", "label": "Vertikal zentrieren", "icon": "/icons/align-middle.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte vertikal zentrieren", "minSelectionCount": 2, "meaning": "Mehrere Objekte vertikal zentrieren", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Vertikal zentrieren", "body": "Mehrere Objekte vertikal zentrieren", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "align-bottom", "label": "Unten ausrichten", "icon": "/icons/align-bottom.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Mehrere Objekte an der unteren Kante ausrichten", "minSelectionCount": 2, "meaning": "Mehrere Objekte an der unteren Kante ausrichten", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Unten ausrichten", "body": "Mehrere Objekte an der unteren Kante ausrichten", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "distribute-horizontal", "label": "Horizontal verteilen", "icon": "/icons/distribute-horizontal.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte mit gleichen horizontalen Abständen verteilen", "minSelectionCount": 2, "meaning": "Objekte mit gleichen horizontalen Abständen verteilen", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Horizontal verteilen", "body": "Objekte mit gleichen horizontalen Abständen verteilen", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "distribute-vertical", "label": "Vertikal verteilen", "icon": "/icons/distribute-vertical.svg", "groupId": "ausrichtung", "art": "aktion", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Objekte mit gleichen vertikalen Abständen verteilen", "minSelectionCount": 2, "meaning": "Objekte mit gleichen vertikalen Abständen verteilen", "usageArea": "Ausrichtung und Verteilung", "group": "Ausrichtung", "tooltip": {"title": "Vertikal verteilen", "body": "Objekte mit gleichen vertikalen Abständen verteilen", "usage": "Einsatzbereich: Ausrichtung und Verteilung"}},
  {"id": "object-style", "label": "Objektstil", "icon": "/icons/object-style.svg", "groupId": "stile", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Gespeicherten Stil auf ein Objekt anwenden", "minSelectionCount": 1, "meaning": "Gespeicherten Stil auf ein Objekt anwenden", "usageArea": "Stile und Standards", "group": "Stile", "tooltip": {"title": "Objektstil", "body": "Gespeicherten Stil auf ein Objekt anwenden", "usage": "Einsatzbereich: Stile und Standards"}},
  {"id": "pages-panel", "label": "Seiten", "icon": "/icons/pages-panel.svg", "groupId": "panels", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Seiten und Musterseiten verwalten", "meaning": "Seiten und Musterseiten verwalten", "usageArea": "Dokumentstruktur", "group": "Panels", "tooltip": {"title": "Seiten", "body": "Seiten und Musterseiten verwalten", "usage": "Einsatzbereich: Dokumentstruktur"}},
  {"id": "layers-panel", "label": "Ebenen", "icon": "/icons/layers-panel.svg", "groupId": "panels", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Ebenen, Sichtbarkeit und Sperren verwalten", "shortcut": "F7", "meaning": "Ebenen, Sichtbarkeit und Sperren verwalten", "usageArea": "Dokumentstruktur", "group": "Panels", "tooltip": {"title": "Ebenen", "body": "Ebenen, Sichtbarkeit und Sperren verwalten", "usage": "Einsatzbereich: Dokumentstruktur", "shortcut": "F7"}},
  {"id": "swatches-panel", "label": "Farbfelder", "icon": "/icons/swatches-panel.svg", "groupId": "panels", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Farben, Verläufe und Sonderfarben verwalten", "shortcut": "F5", "meaning": "Farben, Verläufe und Sonderfarben verwalten", "usageArea": "Farbe und Oberfläche", "group": "Panels", "tooltip": {"title": "Farbfelder", "body": "Farben, Verläufe und Sonderfarben verwalten", "usage": "Einsatzbereich: Farbe und Oberfläche", "shortcut": "F5"}},
  {"id": "preflight", "label": "Preflight", "icon": "/icons/preflight.svg", "groupId": "qualitaet", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Dokument auf technische Fehler prüfen", "meaning": "Dokument auf technische Fehler prüfen", "usageArea": "Qualitätssicherung", "group": "Qualität", "tooltip": {"title": "Preflight", "body": "Dokument auf technische Fehler prüfen", "usage": "Einsatzbereich: Qualitätssicherung"}},
  {"id": "search", "label": "Suche", "icon": "/icons/search.svg", "groupId": "system", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Werkzeuge, Assets oder Inhalte durchsuchen", "shortcut": "Ctrl+F", "meaning": "Werkzeuge, Assets oder Inhalte durchsuchen", "usageArea": "Navigation und Suche", "group": "System", "tooltip": {"title": "Suche", "body": "Werkzeuge, Assets oder Inhalte durchsuchen", "usage": "Einsatzbereich: Navigation und Suche", "shortcut": "Ctrl+F"}},
  {"id": "settings", "label": "Einstellungen", "icon": "/icons/settings.svg", "groupId": "system", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Werkzeug- oder Dokumenteinstellungen öffnen", "meaning": "Werkzeug- oder Dokumenteinstellungen öffnen", "usageArea": "System und Konfiguration", "group": "System", "tooltip": {"title": "Einstellungen", "body": "Werkzeug- oder Dokumenteinstellungen öffnen", "usage": "Einsatzbereich: System und Konfiguration"}},
  {"id": "more", "label": "Weitere Optionen", "icon": "/icons/more.svg", "groupId": "system", "art": "werkzeug", "supportedWorkspaces": [], "supportedViews": [], "helpText": "Zusätzliche kontextbezogene Befehle anzeigen", "meaning": "Zusätzliche kontextbezogene Befehle anzeigen", "usageArea": "Kontextmenü", "group": "System", "tooltip": {"title": "Weitere Optionen", "body": "Zusätzliche kontextbezogene Befehle anzeigen", "usage": "Einsatzbereich: Kontextmenü"}},
];

export function katalogTool(id: string): ToolDefinition | undefined {
  return TOOL_KATALOG.find((t) => t.id === id);
}
