/**
 * AUF-36 — der **Funktionsvertrag** der 110 Werkzeuge als typisierte Daten.
 *
 * **Was das ist:** Je Werkzeug beschreibt der Vertrag, *was* es täte — `commandId`, Familie,
 * Eingaben, Ergebnisse, Vorbedingungen, Seiteneffekte, ob es umkehrbar und protokollpflichtig ist,
 * und welche Dienstmethode es rufen würde. **Es ist eine Beschreibung, keine Ausführung.**
 *
 * **Die Grenze, und sie ist die wichtigste Zeile dieses Moduls:** Hier entsteht **kein zweiter
 * Ausführungsweg.** Es gibt kein `runTool`, keinen Dispatcher, keine Stelle, die `dienstMethode`
 * aufruft. Jede Änderung am Modell läuft weiterhin ausschließlich über `applyCommand` mit inversen
 * Immer-Patches und `CommandAbgelehnt` **vor** der Mutation. Ein zweiter Weg daneben verlöre Undo
 * und die Ablehnungsprüfung — das wäre der teuerste Fehler des ganzen Pakets. `commandId`,
 * `umkehrbar` und `protokollpflichtig` sind **Metadaten am Werkzeug**, sonst nichts.
 *
 * **Warum ein eigenes Modul und kein Feld an `ToolDefinition`:** I2 hat zugesagt, kein Feld der
 * Bestandsform zu ändern oder zu ergänzen; die Richtung der Anpassung ist Vorschrift (Bauordnung,
 * Konflikt-Regel). Der Vertrag hängt deshalb **neben** der Werkzeugdefinition und wird über die id
 * verbunden.
 *
 * **Erzeugt aus** `~/Downloads/hausplaner_svg_tool_functions.zip` → `src/tool-registry.json`,
 * Feld `code`. Die englischen Paket-ids sind über die führende Namenstabelle
 * `docs/planner/eindeutschung-110-paket-ids.md` auf die deutschen UI-ids abgebildet (AUF-31).
 * `commandId` und `dienstMethode` bleiben englisch — das sind **technische Bezeichner** des
 * Vertrags, keine Beschriftungen, die jemand sieht.
 */

export interface WerkzeugVertrag {
  /** Deutsche UI-id des Werkzeugs (AUF-31) — die Klammer zur `ToolDefinition`. */
  werkzeugId: string;
  /** Technischer Command-Name aus dem Vertrag, z. B. `WallCommand`. Metadatum, kein Aufruf. */
  commandId: string;
  /** Eine von 9 Familien: selection · create · modify · view · measurement · import · domain · assign-or-calculate · workflow. */
  familie: string;
  eingaben: readonly string[];
  ergebnisse: readonly string[];
  /** Eine von 12 Vorbedingungen — die Zuordnung zur Aktivierung steht in `vorbedingungen.ts`. */
  vorbedingungen: readonly string[];
  seiteneffekte: readonly string[];
  /** Rückgängig möglich? Metadatum; die Umkehr leistet `applyCommand` über inverse Patches. */
  umkehrbar: boolean;
  /** Protokollpflichtig? Metadatum; ein Audit-Trail wird hier NICHT geschrieben. */
  protokollpflichtig: boolean;
  /** Die Dienstmethode, die dieses Werkzeug rufen WÜRDE. Wird von niemandem aufgerufen. */
  dienstMethode: string;
}

export const WERKZEUG_VERTRAEGE: readonly WerkzeugVertrag[] = [
  {
    werkzeugId: 'auswahl',
    commandId: 'SelectCommand',
    familie: 'selection',
    eingaben: ['pointerPosition', 'selectionMode'],
    ergebnisse: ['selectionIds'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['ui.selection.update', 'propertiesPanel.refresh'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.auswahl.execute(\'select\', input)',
  },
  {
    werkzeugId: 'direktauswahl',
    commandId: 'DirectSelectCommand',
    familie: 'selection',
    eingaben: ['objectId', 'subElementId'],
    ergebnisse: ['activeSubElement'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['ui.selection.update', 'propertiesPanel.refresh'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.auswahl.execute(\'direct-select\', input)',
  },
  {
    werkzeugId: 'lassoauswahl',
    commandId: 'LassoSelectCommand',
    familie: 'selection',
    eingaben: ['screenPolygon'],
    ergebnisse: ['selectionIds'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['ui.selection.update', 'propertiesPanel.refresh'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.auswahl.execute(\'lasso-select\', input)',
  },
  {
    werkzeugId: 'rechteckauswahl',
    commandId: 'BoxSelectCommand',
    familie: 'selection',
    eingaben: ['screenRect', 'crossingMode'],
    ergebnisse: ['selectionIds'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['ui.selection.update', 'propertiesPanel.refresh'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.auswahl.execute(\'box-select\', input)',
  },
  {
    werkzeugId: 'ausblenden',
    commandId: 'HideCommand',
    familie: 'modify',
    eingaben: ['objectIds'],
    ergebnisse: ['visibilityState'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'hide\', input)',
  },
  {
    werkzeugId: 'ausrichten',
    commandId: 'AlignCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'alignment', 'reference'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'align\', input)',
  },
  {
    werkzeugId: 'drehen',
    commandId: 'RotateCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'pivot', 'angleDeg', 'axis'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'rotate\', input)',
  },
  {
    werkzeugId: 'duplizieren',
    commandId: 'DuplicateCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'offset'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'duplicate\', input)',
  },
  {
    werkzeugId: 'einblenden',
    commandId: 'ShowCommand',
    familie: 'modify',
    eingaben: ['objectIds'],
    ergebnisse: ['visibilityState'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'show\', input)',
  },
  {
    werkzeugId: 'entsperren',
    commandId: 'UnlockCommand',
    familie: 'modify',
    eingaben: ['selectionIds'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'unlock\', input)',
  },
  {
    werkzeugId: 'gruppieren',
    commandId: 'GroupCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'groupName'],
    ergebnisse: ['groupId'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'group\', input)',
  },
  {
    werkzeugId: 'horizontal-spiegeln',
    commandId: 'MirrorHorizontalCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'mirrorAxis'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'mirror-horizontal\', input)',
  },
  {
    werkzeugId: 'kopieren',
    commandId: 'CopyCommand',
    familie: 'modify',
    eingaben: ['selectionIds'],
    ergebnisse: ['clipboardPayload'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'copy\', input)',
  },
  {
    werkzeugId: 'loeschen',
    commandId: 'DeleteCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'cascadePolicy'],
    ergebnisse: ['deletedObjectIds', 'dependencyReport'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'delete\', input)',
  },
  {
    werkzeugId: 'skalieren',
    commandId: 'ScaleCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'pivot', 'scaleVector', 'preserveRatio'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'scale\', input)',
  },
  {
    werkzeugId: 'sperren',
    commandId: 'LockCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'lockReason'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'lock\', input)',
  },
  {
    werkzeugId: 'verschieben',
    commandId: 'MoveCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'delta', 'coordinateSystem', 'snapSettings'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'move\', input)',
  },
  {
    werkzeugId: 'verteilen',
    commandId: 'DistributeCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'axis', 'spacingMode'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'distribute\', input)',
  },
  {
    werkzeugId: 'vertikal-spiegeln',
    commandId: 'MirrorVerticalCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'mirrorAxis'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bearbeiten.execute(\'mirror-vertical\', input)',
  },
  {
    werkzeugId: 'teilen',
    commandId: 'SplitCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'operationParameters'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.cad.execute(\'split\', input)',
  },
  {
    werkzeugId: 'trimmen',
    commandId: 'TrimCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'operationParameters'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.cad.execute(\'trim\', input)',
  },
  {
    werkzeugId: 'verbinden',
    commandId: 'JoinCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'operationParameters'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.cad.execute(\'join\', input)',
  },
  {
    werkzeugId: 'verlaengern',
    commandId: 'ExtendCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'operationParameters'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.cad.execute(\'extend\', input)',
  },
  {
    werkzeugId: 'versatz',
    commandId: 'OffsetCommand',
    familie: 'modify',
    eingaben: ['selectionIds', 'operationParameters'],
    ergebnisse: ['updatedObjectIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.cad.execute(\'offset\', input)',
  },
  {
    werkzeugId: 'bogen',
    commandId: 'ArcCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'arc\', input)',
  },
  {
    werkzeugId: 'kreis',
    commandId: 'CircleCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'circle\', input)',
  },
  {
    werkzeugId: 'linie',
    commandId: 'LineCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'line\', input)',
  },
  {
    werkzeugId: 'polygon',
    commandId: 'PolygonCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'polygon\', input)',
  },
  {
    werkzeugId: 'polylinie',
    commandId: 'PolylineCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'polyline\', input)',
  },
  {
    werkzeugId: 'rechteck',
    commandId: 'RectangleCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.zeichnen.execute(\'rectangle\', input)',
  },
  {
    werkzeugId: 'alles-anzeigen',
    commandId: 'FitViewCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'fit-view\', input)',
  },
  {
    werkzeugId: 'fang',
    commandId: 'SnapCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'snap\', input)',
  },
  {
    werkzeugId: 'umkreisen',
    commandId: 'OrbitCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'orbit\', input)',
  },
  {
    werkzeugId: 'hand',
    commandId: 'PanCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'pan\', input)',
  },
  {
    werkzeugId: 'raster',
    commandId: 'GridCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'grid\', input)',
  },
  {
    werkzeugId: 'vergroessern',
    commandId: 'ZoomInCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'zoom-in\', input)',
  },
  {
    werkzeugId: 'verkleinern',
    commandId: 'ZoomOutCommand',
    familie: 'view',
    eingaben: ['viewportId', 'viewParameters'],
    ergebnisse: ['viewportState'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['viewport.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.ansicht.execute(\'zoom-out\', input)',
  },
  {
    werkzeugId: 'bemassen',
    commandId: 'DimensionCommand',
    familie: 'measurement',
    eingaben: ['points', 'measurementOptions'],
    ergebnisse: ['measurementResult'],
    vorbedingungen: ['project.open', 'viewport.ready'],
    seiteneffekte: ['measurementOverlay.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.messen.execute(\'dimension\', input)',
  },
  {
    werkzeugId: 'distanz-messen',
    commandId: 'MeasureDistanceCommand',
    familie: 'measurement',
    eingaben: ['points', 'measurementOptions'],
    ergebnisse: ['measurementResult'],
    vorbedingungen: ['project.open', 'viewport.ready'],
    seiteneffekte: ['measurementOverlay.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.messen.execute(\'measure-distance\', input)',
  },
  {
    werkzeugId: 'flaeche-messen',
    commandId: 'MeasureAreaCommand',
    familie: 'measurement',
    eingaben: ['points', 'measurementOptions'],
    ergebnisse: ['measurementResult'],
    vorbedingungen: ['project.open', 'viewport.ready'],
    seiteneffekte: ['measurementOverlay.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.messen.execute(\'measure-area\', input)',
  },
  {
    werkzeugId: 'volumen-messen',
    commandId: 'MeasureVolumeCommand',
    familie: 'measurement',
    eingaben: ['points', 'measurementOptions'],
    ergebnisse: ['measurementResult'],
    vorbedingungen: ['project.open', 'viewport.ready'],
    seiteneffekte: ['measurementOverlay.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.messen.execute(\'measure-volume\', input)',
  },
  {
    werkzeugId: 'winkel-messen',
    commandId: 'MeasureAngleCommand',
    familie: 'measurement',
    eingaben: ['points', 'measurementOptions'],
    ergebnisse: ['measurementResult'],
    vorbedingungen: ['project.open', 'viewport.ready'],
    seiteneffekte: ['measurementOverlay.update'],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.messen.execute(\'measure-angle\', input)',
  },
  {
    werkzeugId: 'beschneiden',
    commandId: 'CropCommand',
    familie: 'import',
    eingaben: ['source', 'options'],
    ergebnisse: ['importResult'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'crop\', input)',
  },
  {
    werkzeugId: 'bild-importieren',
    commandId: 'ImportImageCommand',
    familie: 'import',
    eingaben: ['source', 'options'],
    ergebnisse: ['importResult'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'import-image\', input)',
  },
  {
    werkzeugId: 'datei-importieren',
    commandId: 'ImportFileCommand',
    familie: 'import',
    eingaben: ['source', 'options'],
    ergebnisse: ['importResult'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'import-file\', input)',
  },
  {
    werkzeugId: 'erkennung-bestaetigen',
    commandId: 'ApproveDetectionCommand',
    familie: 'import',
    eingaben: ['detectionIds', 'approvalMode'],
    ergebnisse: ['integratedObjectIds'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'approve-detection\', input)',
  },
  {
    werkzeugId: 'grundriss-erkennen',
    commandId: 'RecognizeCommand',
    familie: 'import',
    eingaben: ['referenceId', 'region', 'categories', 'recognitionProfile'],
    ergebnisse: ['detectionBatchId'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'recognize\', input)',
  },
  {
    werkzeugId: 'ki-assistent',
    commandId: 'AiAssistantCommand',
    familie: 'import',
    eingaben: ['source', 'options'],
    ergebnisse: ['importResult'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'ai-assistant\', input)',
  },
  {
    werkzeugId: 'kalibrieren',
    commandId: 'CalibrateCommand',
    familie: 'import',
    eingaben: ['referenceId', 'imagePointA', 'imagePointB', 'realDistance', 'unit'],
    ergebnisse: ['scaleFactor', 'confidence'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'calibrate\', input)',
  },
  {
    werkzeugId: 'nordrichtung-setzen',
    commandId: 'SetNorthCommand',
    familie: 'import',
    eingaben: ['source', 'options'],
    ergebnisse: ['importResult'],
    vorbedingungen: ['project.open', 'permission.import'],
    seiteneffekte: ['referenceLayer.update', 'autosave.markDirty'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.import.execute(\'set-north\', input)',
  },
  {
    werkzeugId: 'boden',
    commandId: 'FloorCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'floor\', input)',
  },
  {
    werkzeugId: 'dach',
    commandId: 'RoofCommand',
    familie: 'create',
    eingaben: ['footprint', 'roofType', 'pitch', 'overhang', 'baseLevelId'],
    ergebnisse: ['roofId', 'roofFaceIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'roof\', input)',
  },
  {
    werkzeugId: 'dachfenster',
    commandId: 'RoofWindowCommand',
    familie: 'create',
    eingaben: ['roofFaceId', 'positionUV', 'width', 'height', 'productId'],
    ergebnisse: ['roofWindowId', 'roofOpeningId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'selection.hasRoofFace'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'roof-window\', input)',
  },
  {
    werkzeugId: 'decke',
    commandId: 'SlabCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'slab\', input)',
  },
  {
    werkzeugId: 'aufriss',
    commandId: 'ElevationCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'elevation\', input)',
  },
  {
    werkzeugId: 'fenster',
    commandId: 'WindowCommand',
    familie: 'create',
    eingaben: ['hostWallId', 'position', 'width', 'height', 'sillHeight', 'windowTypeId'],
    ergebnisse: ['windowId', 'openingId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'hostWall.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'window\', input)',
  },
  {
    werkzeugId: 'gaube',
    commandId: 'DormerCommand',
    familie: 'create',
    eingaben: ['roofFaceId', 'dormerType', 'position', 'width', 'height', 'depth'],
    ergebnisse: ['dormerId', 'roofOpeningId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'selection.hasRoofFace'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'dormer\', input)',
  },
  {
    werkzeugId: 'raum',
    commandId: 'RoomCommand',
    familie: 'create',
    eingaben: ['boundaryIds', 'roomTypeId', 'name'],
    ergebnisse: ['roomId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'room\', input)',
  },
  {
    werkzeugId: 'schnitt',
    commandId: 'SectionCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'section\', input)',
  },
  {
    werkzeugId: 'stuetze',
    commandId: 'ColumnCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'column\', input)',
  },
  {
    werkzeugId: 'treppe',
    commandId: 'StairsCommand',
    familie: 'create',
    eingaben: ['fromLevelId', 'toLevelId', 'stairType', 'width', 'openingGeometry'],
    ergebnisse: ['stairId', 'slabOpeningId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'stairs\', input)',
  },
  {
    werkzeugId: 'tuer',
    commandId: 'DoorCommand',
    familie: 'create',
    eingaben: ['hostWallId', 'position', 'width', 'height', 'swing', 'doorTypeId'],
    ergebnisse: ['doorId', 'openingId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'hostWall.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'door\', input)',
  },
  {
    werkzeugId: 'unterzug',
    commandId: 'BeamCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'beam\', input)',
  },
  {
    werkzeugId: 'wand',
    commandId: 'WallCommand',
    familie: 'create',
    eingaben: ['startPoint', 'endPoint', 'wallTypeId', 'height', 'thickness', 'referenceLine'],
    ergebnisse: ['wallId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'wall\', input)',
  },
  {
    werkzeugId: 'oeffnung',
    commandId: 'OpeningCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.architektur.execute(\'opening\', input)',
  },
  {
    werkzeugId: 'fassadensystem',
    commandId: 'FacadeCommand',
    familie: 'assign-or-calculate',
    eingaben: ['objectIds', 'parameters'],
    ergebnisse: ['assignmentOrResultIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.fassade.execute(\'facade\', input)',
  },
  {
    werkzeugId: 'klinker',
    commandId: 'BrickCommand',
    familie: 'assign-or-calculate',
    eingaben: ['objectIds', 'parameters'],
    ergebnisse: ['assignmentOrResultIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.fassade.execute(\'brick\', input)',
  },
  {
    werkzeugId: 'material-aufnehmen',
    commandId: 'PaintCommand',
    familie: 'assign-or-calculate',
    eingaben: ['objectIds', 'parameters'],
    ergebnisse: ['assignmentOrResultIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.material.execute(\'paint\', input)',
  },
  {
    werkzeugId: 'material-zuweisen',
    commandId: 'MaterialCommand',
    familie: 'assign-or-calculate',
    eingaben: ['objectIds', 'surfaceSlot', 'surfaceMaterialId', 'variantId'],
    ergebnisse: ['materialAssignmentIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.material.execute(\'material\', input)',
  },
  {
    werkzeugId: 'textur',
    commandId: 'TextureCommand',
    familie: 'assign-or-calculate',
    eingaben: ['materialAssignmentId', 'textureSetId', 'mapping'],
    ergebnisse: ['updatedAssignmentId'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.material.execute(\'texture\', input)',
  },
  {
    werkzeugId: 'daemmung',
    commandId: 'InsulationCommand',
    familie: 'assign-or-calculate',
    eingaben: ['objectIds', 'parameters'],
    ergebnisse: ['assignmentOrResultIds'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bauphysik.execute(\'insulation\', input)',
  },
  {
    werkzeugId: 'lueftung',
    commandId: 'VentilationCommand',
    familie: 'assign-or-calculate',
    eingaben: ['roomIds', 'systemType', 'airChangeRate', 'heatRecovery'],
    ergebnisse: ['ventilationZoneId'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bauphysik.execute(\'ventilation\', input)',
  },
  {
    werkzeugId: 'thermische-huelle',
    commandId: 'ThermalEnvelopeCommand',
    familie: 'assign-or-calculate',
    eingaben: ['componentIds', 'boundaryType', 'adjacentZoneId'],
    ergebnisse: ['envelopeAssignments'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bauphysik.execute(\'thermal-envelope\', input)',
  },
  {
    werkzeugId: 'u-wert',
    commandId: 'UValueCommand',
    familie: 'assign-or-calculate',
    eingaben: ['componentId', 'assemblyId', 'manualOverride'],
    ergebnisse: ['uValue', 'calculationSource'],
    vorbedingungen: ['project.open', 'selection.count >= 1', 'permission.edit', 'component.thermalRelevant'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bauphysik.execute(\'u-value\', input)',
  },
  {
    werkzeugId: 'fussbodenheizung',
    commandId: 'FloorHeatingCommand',
    familie: 'create',
    eingaben: ['roomId', 'heatingArea', 'exclusionAreas', 'pipeType', 'spacing'],
    ergebnisse: ['circuitIds', 'pipeLength', 'flowRates'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.heizung.execute(\'floor-heating\', input)',
  },
  {
    werkzeugId: 'heizkoerper',
    commandId: 'RadiatorCommand',
    familie: 'create',
    eingaben: ['roomId', 'position', 'productId', 'designTemperatures'],
    ergebnisse: ['radiatorId', 'designOutput', 'flowRate'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.heizung.execute(\'radiator\', input)',
  },
  {
    werkzeugId: 'hydraulischer-abgleich',
    commandId: 'HydraulicBalanceCommand',
    familie: 'domain',
    eingaben: ['networkId', 'designTemperatures', 'pumpData'],
    ergebnisse: ['balanceRunId', 'valveSettings'],
    vorbedingungen: ['project.open', 'heatingNetwork.connected', 'heatEmitters.sized'],
    seiteneffekte: [],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.heizung.execute(\'hydraulic-balance\', input)',
  },
  {
    werkzeugId: 'pumpe',
    commandId: 'PumpCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.heizung.execute(\'pump\', input)',
  },
  {
    werkzeugId: 'waermepumpe',
    commandId: 'HeatPumpCommand',
    familie: 'create',
    eingaben: ['projectId', 'placement', 'productId', 'designPoint'],
    ergebnisse: ['heatPumpSystemId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'heatingLoad.approved'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.heizung.execute(\'heat-pump\', input)',
  },
  {
    werkzeugId: 'rohrleitung',
    commandId: 'PipeCommand',
    familie: 'create',
    eingaben: ['systemId', 'path', 'dimension', 'elevation', 'slope'],
    ergebnisse: ['pipeSegmentIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.tga.execute(\'pipe\', input)',
  },
  {
    werkzeugId: 'badewanne',
    commandId: 'BathCommand',
    familie: 'create',
    eingaben: ['roomId', 'position', 'productId'],
    ergebnisse: ['bathObjectId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bad.execute(\'bath\', input)',
  },
  {
    werkzeugId: 'dusche',
    commandId: 'ShowerCommand',
    familie: 'create',
    eingaben: ['roomId', 'position', 'size', 'drainType'],
    ergebnisse: ['showerId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bad.execute(\'shower\', input)',
  },
  {
    werkzeugId: 'wc',
    commandId: 'ToiletCommand',
    familie: 'create',
    eingaben: ['roomId', 'position', 'productId', 'connectionPortId'],
    ergebnisse: ['toiletId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.bad.execute(\'toilet\', input)',
  },
  {
    werkzeugId: 'geraet',
    commandId: 'ApplianceCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.kueche.execute(\'appliance\', input)',
  },
  {
    werkzeugId: 'kuechenplanung',
    commandId: 'KitchenCommand',
    familie: 'create',
    eingaben: ['roomId', 'layoutType', 'workZones'],
    ergebnisse: ['kitchenPlanId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.kueche.execute(\'kitchen\', input)',
  },
  {
    werkzeugId: 'schrank',
    commandId: 'CabinetCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.kueche.execute(\'cabinet\', input)',
  },
  {
    werkzeugId: 'sanitaeranschluss',
    commandId: 'SanitaryCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.sanitaer.execute(\'sanitary\', input)',
  },
  {
    werkzeugId: 'elektroplanung',
    commandId: 'ElectricCommand',
    familie: 'domain',
    eingaben: ['projectId', 'planningProfile'],
    ergebnisse: ['electricalPlanId'],
    vorbedingungen: ['project.open'],
    seiteneffekte: [],
    umkehrbar: false,
    protokollpflichtig: false,
    dienstMethode: 'services.elektro.execute(\'electric\', input)',
  },
  {
    werkzeugId: 'leuchte',
    commandId: 'LightCommand',
    familie: 'create',
    eingaben: ['hostId', 'position', 'lightType', 'circuitId'],
    ergebnisse: ['lightId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.elektro.execute(\'light\', input)',
  },
  {
    werkzeugId: 'schalter',
    commandId: 'SwitchCommand',
    familie: 'create',
    eingaben: ['hostId', 'position', 'mountingHeight', 'switchType', 'controlledIds'],
    ergebnisse: ['switchId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.elektro.execute(\'switch\', input)',
  },
  {
    werkzeugId: 'steckdose',
    commandId: 'SocketCommand',
    familie: 'create',
    eingaben: ['hostId', 'position', 'mountingHeight', 'socketType', 'circuitId'],
    ergebnisse: ['socketId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.elektro.execute(\'socket\', input)',
  },
  {
    werkzeugId: 'verteiler',
    commandId: 'DistributionBoardCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.elektro.execute(\'distribution-board\', input)',
  },
  {
    werkzeugId: 'batteriespeicher',
    commandId: 'BatteryCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.pv.execute(\'battery\', input)',
  },
  {
    werkzeugId: 'pv-modul',
    commandId: 'PvModuleCommand',
    familie: 'create',
    eingaben: ['roofFaceId', 'moduleProductId', 'layoutPosition', 'orientation'],
    ergebnisse: ['pvModuleId'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists', 'selection.hasRoofFace'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.pv.execute(\'pv-module\', input)',
  },
  {
    werkzeugId: 'wallbox',
    commandId: 'WallboxCommand',
    familie: 'create',
    eingaben: ['placement', 'parameters', 'activeLevelId'],
    ergebnisse: ['createdObjectIds'],
    vorbedingungen: ['project.open', 'permission.edit', 'activeLevel.exists'],
    seiteneffekte: ['model.revision.increment', 'autosave.markDirty', 'dependentResults.invalidate', 'renderer.refreshAffectedObjects'],
    umkehrbar: true,
    protokollpflichtig: true,
    dienstMethode: 'services.pv.execute(\'wallbox\', input)',
  },
  {
    werkzeugId: 'freigeben',
    commandId: 'ApproveCommand',
    familie: 'workflow',
    eingaben: ['subjectId', 'approvalType', 'comment'],
    ergebnisse: ['approvalId'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.workflow.execute(\'approve\', input)',
  },
  {
    werkzeugId: 'prozessuebersicht',
    commandId: 'WorkflowCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.workflow.execute(\'workflow\', input)',
  },
  {
    werkzeugId: 'assistent',
    commandId: 'WizardCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.workflow.execute(\'wizard\', input)',
  },
  {
    werkzeugId: 'uebergabepaket',
    commandId: 'HandoffPackageCommand',
    familie: 'workflow',
    eingaben: ['processId', 'targetModule', 'sourceRevision', 'objectIds'],
    ergebnisse: ['packageId', 'inputHash'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.workflow.execute(\'handoff-package\', input)',
  },
  {
    werkzeugId: 'fehler',
    commandId: 'ErrorCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.pruefung.execute(\'error\', input)',
  },
  {
    werkzeugId: 'pruefen',
    commandId: 'CheckCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.pruefung.execute(\'check\', input)',
  },
  {
    werkzeugId: 'warnungen',
    commandId: 'WarningCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.pruefung.execute(\'warning\', input)',
  },
  {
    werkzeugId: 'historie',
    commandId: 'HistoryCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.zusammenarbeit.execute(\'history\', input)',
  },
  {
    werkzeugId: 'kommentar',
    commandId: 'CommentCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.zusammenarbeit.execute(\'comment\', input)',
  },
  {
    werkzeugId: 'revision',
    commandId: 'RevisionCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.zusammenarbeit.execute(\'revision\', input)',
  },
  {
    werkzeugId: 'befehlspalette',
    commandId: 'CommandPaletteCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.system.execute(\'command-palette\', input)',
  },
  {
    werkzeugId: 'einstellungen',
    commandId: 'SettingsCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.system.execute(\'settings\', input)',
  },
  {
    werkzeugId: 'exportieren',
    commandId: 'ExportCommand',
    familie: 'workflow',
    eingaben: ['scope', 'format', 'options'],
    ergebnisse: ['exportJobId'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.system.execute(\'export\', input)',
  },
  {
    werkzeugId: 'pdf',
    commandId: 'PdfCommand',
    familie: 'workflow',
    eingaben: ['sheetIds', 'pdfProfile'],
    ergebnisse: ['pdfJobId'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.system.execute(\'pdf\', input)',
  },
  {
    werkzeugId: 'suche',
    commandId: 'SearchCommand',
    familie: 'workflow',
    eingaben: ['subjectIds', 'workflowParameters'],
    ergebnisse: ['workflowResult'],
    vorbedingungen: ['project.open'],
    seiteneffekte: ['workflowState.update', 'auditLog.append'],
    umkehrbar: false,
    protokollpflichtig: true,
    dienstMethode: 'services.system.execute(\'search\', input)',
  },];

const NACH_ID = new Map(WERKZEUG_VERTRAEGE.map((v) => [v.werkzeugId, v]));

/** Der Vertrag eines Werkzeugs (oder undefined). */
export function vertrag(werkzeugId: string): WerkzeugVertrag | undefined {
  return NACH_ID.get(werkzeugId);
}

/** Alle Verträge einer Familie. */
export function vertraegeDerFamilie(familie: string): WerkzeugVertrag[] {
  return WERKZEUG_VERTRAEGE.filter((v) => v.familie === familie);
}

/** Die Vokabulare, gezählt aus den Daten — nicht hart hinterlegt, damit sie nicht auseinanderlaufen. */
export function vokabular(): { vorbedingungen: string[]; seiteneffekte: string[]; familien: string[] } {
  const sammle = (f: (v: WerkzeugVertrag) => readonly string[]): string[] =>
    [...new Set(WERKZEUG_VERTRAEGE.flatMap((v) => f(v)))].sort();
  return {
    vorbedingungen: sammle((v) => v.vorbedingungen),
    seiteneffekte: sammle((v) => v.seiteneffekte),
    familien: sammle((v) => [v.familie]),
  };
}

/** Werkzeug-ids mit mehr als einem Vertrag — muss leer sein. */
export function doppelteVertraege(): string[] {
  const zaehler = new Map<string, number>();
  for (const v of WERKZEUG_VERTRAEGE) zaehler.set(v.werkzeugId, (zaehler.get(v.werkzeugId) ?? 0) + 1);
  return [...zaehler].filter(([, n]) => n > 1).map(([id]) => id);
}
