/**
 * I2 (AUF-21) — das 110er-Werkzeugpaket als typisierte Daten.
 *
 * **Erzeugt aus** `docs/planner/tool-registry-paket.json` (110 Einträge, Yamas Paket). Als TS-Modul
 * abgelegt und nicht zur Laufzeit aus JSON geladen — genauso wie der bisherige Katalog: die Daten
 * sind damit typgeprüft, im Bundle ohne Ladeschritt und im Diff lesbar.
 *
 * **Feldnamen deutsch**, dem Yama-Entscheid „alles deutsch" folgend (`14e6346`). Die **ids bleiben
 * unverändert aus dem Paket** — sie sind zugleich der Dateiname des Icons
 * (`public/hausplaner/icons/tools/<id>.svg`, I1 `7bbf9ff`). Eine Eindeutschung der ids wäre eine
 * eigene Entscheidung mit Wirkung auf 110 Dateinamen; sie steht im Bericht als Frage an Yama.
 *
 * Zwei Felder tragen mehr als Beiwerk und sind der Grund, warum das Paket überhaupt hier landet:
 * `anheftbar` (canPin) ist der Werkzeug-Zustand „angeheftet", `prioritaet` bildet ab, was die
 * Zonen-Kuratierung heute von Hand pflegt. **Verwendet werden sie in I3, nicht hier.**
 */

/** Ein Werkzeug aus Yamas Paket — Rohform, noch nicht auf `ToolDefinition` abgebildet. */
export interface PaketWerkzeug {
  id: string;
  label: string;
  kategorie: string;
  icon: string;
  variante: string;
  funktion: string;
  einsatz: string;
  ansichten: readonly string[];
  prioritaet: 'primary' | 'secondary';
  anheftbar: boolean;
  shortcut?: string;
}

/** Die 110 Fach-Werkzeuge. Reihenfolge = Paket-Reihenfolge (Kategorie-Gruppen). */
export const PAKET_WERKZEUGE: readonly PaketWerkzeug[] = [
  { id: 'select', label: 'Auswahl', kategorie: 'Auswahl', icon: 'icons/select.svg', variante: 'cursor',
    funktion: 'Einzelne Objekte auswählen.',
    einsatz: 'Alle Workspaces; Ausgangspunkt jeder Bearbeitung.',
    ansichten: ['2D', '3D'], prioritaet: 'primary', anheftbar: true, shortcut: 'V' },
  { id: 'direct-select', label: 'Direktauswahl', kategorie: 'Auswahl', icon: 'icons/direct-select.svg', variante: 'cursor-direct',
    funktion: 'Punkte, Kanten oder Teilflächen auswählen.',
    einsatz: 'Geometrische Detailkorrektur.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'A' },
  { id: 'box-select', label: 'Rechteckauswahl', kategorie: 'Auswahl', icon: 'icons/box-select.svg', variante: 'box-select',
    funktion: 'Mehrere Objekte mit Auswahlrahmen erfassen.',
    einsatz: 'Grundriss, Fassaden, technische Netze.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'lasso-select', label: 'Lassoauswahl', kategorie: 'Auswahl', icon: 'icons/lasso-select.svg', variante: 'lasso',
    funktion: 'Unregelmäßige Objektgruppen auswählen.',
    einsatz: 'Komplexe Grundrisse und TGA-Bereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'move', label: 'Verschieben', kategorie: 'Bearbeiten', icon: 'icons/move.svg', variante: 'move',
    funktion: 'Objekte entlang X, Y oder Z verschieben.',
    einsatz: 'Alle bearbeitbaren Fachobjekte.',
    ansichten: ['2D', '3D'], prioritaet: 'primary', anheftbar: true, shortcut: 'G' },
  { id: 'rotate', label: 'Drehen', kategorie: 'Bearbeiten', icon: 'icons/rotate.svg', variante: 'rotate',
    funktion: 'Objekte um einen Bezugspunkt drehen.',
    einsatz: 'Möbel, Bauteile, Referenzen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'R' },
  { id: 'scale', label: 'Skalieren', kategorie: 'Bearbeiten', icon: 'icons/scale.svg', variante: 'scale',
    funktion: 'Freie Geometrie proportional oder achsweise skalieren.',
    einsatz: 'Importe, Referenzen und freie Objekte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'S' },
  { id: 'mirror-horizontal', label: 'Horizontal spiegeln', kategorie: 'Bearbeiten', icon: 'icons/mirror-horizontal.svg', variante: 'mirror-h',
    funktion: 'Objekt an vertikaler Achse spiegeln.',
    einsatz: 'Grundrisse, Türen, Fensterteilungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'mirror-vertical', label: 'Vertikal spiegeln', kategorie: 'Bearbeiten', icon: 'icons/mirror-vertical.svg', variante: 'mirror-v',
    funktion: 'Objekt an horizontaler Achse spiegeln.',
    einsatz: 'Dachkonturen, Symmetrien.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'copy', label: 'Kopieren', kategorie: 'Bearbeiten', icon: 'icons/copy.svg', variante: 'copy',
    funktion: 'Auswahl in Zwischenablage kopieren.',
    einsatz: 'Alle Workspaces.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+C' },
  { id: 'duplicate', label: 'Duplizieren', kategorie: 'Bearbeiten', icon: 'icons/duplicate.svg', variante: 'copy',
    funktion: 'Sofortige Kopie am aktuellen Ort erzeugen.',
    einsatz: 'Fenster, Möbel, technische Objekte.',
    ansichten: ['2D', '3D'], prioritaet: 'primary', anheftbar: true, shortcut: 'Ctrl/Cmd+D' },
  { id: 'delete', label: 'Löschen', kategorie: 'Bearbeiten', icon: 'icons/delete.svg', variante: 'delete',
    funktion: 'Auswahl nach Abhängigkeitsprüfung entfernen.',
    einsatz: 'Alle bearbeitbaren Objekte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Delete' },
  { id: 'lock', label: 'Sperren', kategorie: 'Bearbeiten', icon: 'icons/lock.svg', variante: 'lock',
    funktion: 'Objekt vor Änderungen schützen.',
    einsatz: 'Referenzen, freigegebene Bauteile.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'unlock', label: 'Entsperren', kategorie: 'Bearbeiten', icon: 'icons/unlock.svg', variante: 'unlock',
    funktion: 'Bearbeitung gesperrter Objekte zulassen.',
    einsatz: 'Berechtigte Nutzer.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'show', label: 'Einblenden', kategorie: 'Bearbeiten', icon: 'icons/show.svg', variante: 'eye',
    funktion: 'Ausgeblendete Objekte sichtbar machen.',
    einsatz: 'Layer- und Modellsteuerung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'hide', label: 'Ausblenden', kategorie: 'Bearbeiten', icon: 'icons/hide.svg', variante: 'eye-off',
    funktion: 'Objekte temporär ausblenden.',
    einsatz: 'Koordination und Modellprüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'group', label: 'Gruppieren', kategorie: 'Bearbeiten', icon: 'icons/group.svg', variante: 'group',
    funktion: 'Mehrere Objekte als Gruppe behandeln.',
    einsatz: 'Möbel, Symbole, technische Komponenten.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'align', label: 'Ausrichten', kategorie: 'Bearbeiten', icon: 'icons/align.svg', variante: 'align',
    funktion: 'Objekte an Kante, Achse oder Mitte ausrichten.',
    einsatz: 'Innenraum, Fassaden, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'distribute', label: 'Verteilen', kategorie: 'Bearbeiten', icon: 'icons/distribute.svg', variante: 'distribute',
    funktion: 'Objekte gleichmäßig verteilen.',
    einsatz: 'Fenster, Leuchten, PV-Module.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'line', label: 'Linie', kategorie: 'Zeichnen', icon: 'icons/line.svg', variante: 'line',
    funktion: 'Gerade Linie zwischen zwei Punkten zeichnen.',
    einsatz: 'Hilfsgeometrie und technische Zeichnung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'L' },
  { id: 'polyline', label: 'Polylinie', kategorie: 'Zeichnen', icon: 'icons/polyline.svg', variante: 'polyline',
    funktion: 'Zusammenhängende Liniensegmente zeichnen.',
    einsatz: 'Konturen, Leitungswege und Grundstücke.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'rectangle', label: 'Rechteck', kategorie: 'Zeichnen', icon: 'icons/rectangle.svg', variante: 'rectangle',
    funktion: 'Rechteckige Kontur erzeugen.',
    einsatz: 'Räume, Öffnungen und Flächen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'polygon', label: 'Polygon', kategorie: 'Zeichnen', icon: 'icons/polygon.svg', variante: 'polygon',
    funktion: 'Freie geschlossene Kontur zeichnen.',
    einsatz: 'Dächer, Grundstücke und Zonen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'circle', label: 'Kreis', kategorie: 'Zeichnen', icon: 'icons/circle.svg', variante: 'circle',
    funktion: 'Kreis über Mittelpunkt und Radius erzeugen.',
    einsatz: 'Runde Bauteile und Schächte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'arc', label: 'Bogen', kategorie: 'Zeichnen', icon: 'icons/arc.svg', variante: 'arc',
    funktion: 'Kreisbogen oder tangentialen Bogen erzeugen.',
    einsatz: 'Bogenwände und Leitungsführung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'trim', label: 'Trimmen', kategorie: 'CAD', icon: 'icons/trim.svg', variante: 'trim',
    funktion: 'Überstehende Linien an Begrenzungen abschneiden.',
    einsatz: 'Grundriss- und Detailkorrektur.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'extend', label: 'Verlängern', kategorie: 'CAD', icon: 'icons/extend.svg', variante: 'extend',
    funktion: 'Linien bis zu einer Begrenzung verlängern.',
    einsatz: 'Wände, Achsen, Leitungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'offset', label: 'Versatz', kategorie: 'CAD', icon: 'icons/offset.svg', variante: 'offset',
    funktion: 'Parallele Kopie mit festem Abstand erzeugen.',
    einsatz: 'Wände, Installationszonen, Dachüberstand.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'split', label: 'Teilen', kategorie: 'CAD', icon: 'icons/split.svg', variante: 'split',
    funktion: 'Linie oder Fachobjekt an einem Punkt teilen.',
    einsatz: 'Wände, Leitungen, Dachflächen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'join', label: 'Verbinden', kategorie: 'CAD', icon: 'icons/join.svg', variante: 'join',
    funktion: 'Getrennte Segmente oder Objekte verbinden.',
    einsatz: 'Konturen, Leitungsnetze.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'wall', label: 'Wand', kategorie: 'Architektur', icon: 'icons/wall.svg', variante: 'wall',
    funktion: 'Parametrische Wand mit Aufbau, Höhe und Dicke erzeugen.',
    einsatz: 'Architektur, Bauphysik, Heizlast.',
    ansichten: ['2D', '3D'], prioritaet: 'primary', anheftbar: true, shortcut: 'W' },
  { id: 'room', label: 'Raum', kategorie: 'Architektur', icon: 'icons/room.svg', variante: 'room',
    funktion: 'Geschlossene Raumkontur erkennen oder erzeugen.',
    einsatz: 'Grundriss, Heizlast, Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'door', label: 'Tür', kategorie: 'Architektur', icon: 'icons/door.svg', variante: 'door',
    funktion: 'Türöffnung und Türelement platzieren.',
    einsatz: 'Architektur, Bad, Küche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'window', label: 'Fenster', kategorie: 'Architektur', icon: 'icons/window.svg', variante: 'window',
    funktion: 'Fenster mit Profil, Glas und Öffnungsart platzieren.',
    einsatz: 'Architektur, Fassade, Heizlast.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'stairs', label: 'Treppe', kategorie: 'Architektur', icon: 'icons/stairs.svg', variante: 'stairs',
    funktion: 'Treppe zwischen Ebenen parametrisch erzeugen.',
    einsatz: 'Erschließung und Schnittplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'roof', label: 'Dach', kategorie: 'Architektur', icon: 'icons/roof.svg', variante: 'roof',
    funktion: 'Dach aus Kontur oder Dachform erzeugen.',
    einsatz: 'Dachplanung und Bauphysik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'dormer', label: 'Gaube', kategorie: 'Architektur', icon: 'icons/dormer.svg', variante: 'dormer',
    funktion: 'Gaube mit Dachöffnung und Seitenwänden einsetzen.',
    einsatz: 'Dachplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'roof-window', label: 'Dachfenster', kategorie: 'Architektur', icon: 'icons/roof-window.svg', variante: 'roof-window',
    funktion: 'Dachfenster in geneigter Dachfläche platzieren.',
    einsatz: 'Dachplanung, Heizlast.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'column', label: 'Stütze', kategorie: 'Architektur', icon: 'icons/column.svg', variante: 'column',
    funktion: 'Tragende oder gestalterische Stütze setzen.',
    einsatz: 'Architektur und Tragwerk.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'beam', label: 'Unterzug / Träger', kategorie: 'Architektur', icon: 'icons/beam.svg', variante: 'beam',
    funktion: 'Horizontalen Träger oder Unterzug erzeugen.',
    einsatz: 'Tragwerk und Kollisionsprüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'opening', label: 'Öffnung', kategorie: 'Architektur', icon: 'icons/opening.svg', variante: 'opening',
    funktion: 'Durchbruch in Wand, Decke, Boden oder Dach erzeugen.',
    einsatz: 'Architektur und TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'floor', label: 'Boden', kategorie: 'Architektur', icon: 'icons/floor.svg', variante: 'floor',
    funktion: 'Bodenfläche und Bodenaufbau erzeugen.',
    einsatz: 'Innenraum, Bauphysik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'slab', label: 'Decke / Bodenplatte', kategorie: 'Architektur', icon: 'icons/slab.svg', variante: 'slab',
    funktion: 'Massive oder mehrschichtige Decke erzeugen.',
    einsatz: 'Architektur, Statik, Heizlast.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'section', label: 'Schnitt', kategorie: 'Architektur', icon: 'icons/section.svg', variante: 'section',
    funktion: 'Schnittlinie und abgeleitete Schnittansicht erzeugen.',
    einsatz: 'Treppen, Dächer, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'elevation', label: 'Fassade / Ansicht', kategorie: 'Architektur', icon: 'icons/elevation.svg', variante: 'elevation',
    funktion: 'Orthogonale Gebäudeansicht erzeugen.',
    einsatz: 'Fassade, Fenster, Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'zoom-in', label: 'Vergrößern', kategorie: 'Ansicht', icon: 'icons/zoom-in.svg', variante: 'zoom-in',
    funktion: 'Ansicht schrittweise vergrößern.',
    einsatz: 'Detailbearbeitung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: '+' },
  { id: 'zoom-out', label: 'Verkleinern', kategorie: 'Ansicht', icon: 'icons/zoom-out.svg', variante: 'zoom-out',
    funktion: 'Ansicht schrittweise verkleinern.',
    einsatz: 'Modellübersicht.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: '-' },
  { id: 'fit-view', label: 'Alles anzeigen', kategorie: 'Ansicht', icon: 'icons/fit-view.svg', variante: 'fit',
    funktion: 'Modell oder Referenz vollständig einpassen.',
    einsatz: 'Alle Workspaces.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Shift+F' },
  { id: 'pan', label: 'Pan / Hand', kategorie: 'Ansicht', icon: 'icons/pan.svg', variante: 'pan',
    funktion: 'Canvas verschieben, ohne Geometrie zu ändern.',
    einsatz: '2D und 3D.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Space' },
  { id: 'orbit', label: 'Orbit', kategorie: 'Ansicht', icon: 'icons/orbit.svg', variante: 'orbit',
    funktion: '3D-Kamera um Fokuspunkt drehen.',
    einsatz: '3D-Ansicht.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'grid', label: 'Raster', kategorie: 'Ansicht', icon: 'icons/grid.svg', variante: 'grid',
    funktion: 'Zeichenraster ein- oder ausblenden.',
    einsatz: '2D, Import, Grundriss.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'G' },
  { id: 'snap', label: 'Fang', kategorie: 'Ansicht', icon: 'icons/snap.svg', variante: 'snap',
    funktion: 'Fang an Raster, Kanten, End- und Schnittpunkten.',
    einsatz: 'Präzises Zeichnen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'S' },
  { id: 'measure-distance', label: 'Distanz messen', kategorie: 'Messen', icon: 'icons/measure-distance.svg', variante: 'measure',
    funktion: 'Temporäre Distanz zwischen zwei Punkten messen.',
    einsatz: 'Alle Planungsbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'M' },
  { id: 'dimension', label: 'Bemaßen', kategorie: 'Messen', icon: 'icons/dimension.svg', variante: 'dimension',
    funktion: 'Persistente technische Maßlinie erzeugen.',
    einsatz: '2D, Schnitt, Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'measure-angle', label: 'Winkel messen', kategorie: 'Messen', icon: 'icons/measure-angle.svg', variante: 'angle',
    funktion: 'Winkel zwischen Linien oder Flächen messen.',
    einsatz: 'Dach, Treppe, Leitungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'measure-area', label: 'Fläche messen', kategorie: 'Messen', icon: 'icons/measure-area.svg', variante: 'area',
    funktion: 'Geschlossene Fläche ermitteln.',
    einsatz: 'Räume, Fassaden, Dächer.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'measure-volume', label: 'Volumen messen', kategorie: 'Messen', icon: 'icons/measure-volume.svg', variante: 'volume',
    funktion: 'Körper- oder Raumvolumen ermitteln.',
    einsatz: 'Heizlast, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'import-file', label: 'Datei importieren', kategorie: 'Import', icon: 'icons/import-file.svg', variante: 'import',
    funktion: 'PDF, Bild, DWG, DXF, IFC oder SVG laden.',
    einsatz: 'Import & Nachzeichnen.',
    ansichten: ['2D'], prioritaet: 'primary', anheftbar: true, shortcut: 'I' },
  { id: 'import-image', label: 'Bild importieren', kategorie: 'Import', icon: 'icons/import-image.svg', variante: 'image',
    funktion: 'Rasterbild oder Scan als Referenz laden.',
    einsatz: 'Bestandsgrundrisse.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'calibrate', label: 'Kalibrieren', kategorie: 'Import', icon: 'icons/calibrate.svg', variante: 'calibrate',
    funktion: 'Bildmaßstab über bekannte Strecke bestimmen.',
    einsatz: 'Grundrissimport.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'crop', label: 'Beschneiden', kategorie: 'Import', icon: 'icons/crop.svg', variante: 'crop',
    funktion: 'Referenz auf relevanten Bereich beschneiden.',
    einsatz: 'PDF und Bild.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'set-north', label: 'Nordrichtung setzen', kategorie: 'Import', icon: 'icons/set-north.svg', variante: 'north',
    funktion: 'Nordrichtung und Gebäudebezug festlegen.',
    einsatz: 'Import, PV, Verschattung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'recognize', label: 'Grundriss erkennen', kategorie: 'Import', icon: 'icons/recognize.svg', variante: 'detect',
    funktion: 'Wände, Räume, Fenster, Türen und Maße erkennen.',
    einsatz: 'KI-/Regelerkennung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'ai-assistant', label: 'KI-Assistent', kategorie: 'Import', icon: 'icons/ai-assistant.svg', variante: 'ai',
    funktion: 'Vorschläge, Erkennung und Korrektur unterstützen.',
    einsatz: 'Import, Planung, Prüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'approve-detection', label: 'Erkennung bestätigen', kategorie: 'Import', icon: 'icons/approve-detection.svg', variante: 'check',
    funktion: 'Erkanntes Objekt als Fachobjekt übernehmen.',
    einsatz: 'Review-Modus.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'material', label: 'Material zuweisen', kategorie: 'Material', icon: 'icons/material.svg', variante: 'material',
    funktion: 'Technisches oder sichtbares Material zuordnen.',
    einsatz: 'Fassade, Fenster, Türen, Dach.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'texture', label: 'Textur / PBR', kategorie: 'Material', icon: 'icons/texture.svg', variante: 'texture',
    funktion: 'PBR-Texturensatz und Mapping wählen.',
    einsatz: '3D-Darstellung und Rendering.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'paint', label: 'Material aufnehmen', kategorie: 'Material', icon: 'icons/paint.svg', variante: 'paint',
    funktion: 'Material von Objekt übernehmen und übertragen.',
    einsatz: 'Innenraum und Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'facade', label: 'Fassadensystem', kategorie: 'Fassade', icon: 'icons/facade.svg', variante: 'facade',
    funktion: 'Putz, Klinker, Holz oder Plattensystem zuweisen.',
    einsatz: 'Fassadenplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'brick', label: 'Klinker / Verband', kategorie: 'Fassade', icon: 'icons/brick.svg', variante: 'brick',
    funktion: 'Klinkerformat, Fuge und Verband konfigurieren.',
    einsatz: 'Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'insulation', label: 'Dämmung', kategorie: 'Bauphysik', icon: 'icons/insulation.svg', variante: 'insulation',
    funktion: 'Dämmstoff und Dämmstärke festlegen.',
    einsatz: 'Wand, Dach, Decke, Boden.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'u-value', label: 'U-Wert', kategorie: 'Bauphysik', icon: 'icons/u-value.svg', variante: 'uvalue',
    funktion: 'U-Wert berechnen, prüfen oder überschreiben.',
    einsatz: 'Heizlast und Bauphysik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'thermal-envelope', label: 'Thermische Hülle', kategorie: 'Bauphysik', icon: 'icons/thermal-envelope.svg', variante: 'thermal',
    funktion: 'Wärmeübertragende Gebäudehülle markieren.',
    einsatz: 'Heizlast-Datencheck.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'ventilation', label: 'Lüftung', kategorie: 'Bauphysik', icon: 'icons/ventilation.svg', variante: 'ventilation',
    funktion: 'Lüftungszonen und Luftwechsel definieren.',
    einsatz: 'Heizlast und TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'radiator', label: 'Heizkörper', kategorie: 'Heizung', icon: 'icons/radiator.svg', variante: 'radiator',
    funktion: 'Heizkörper platzieren und auf Raumheizlast auslegen.',
    einsatz: 'Heizung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'floor-heating', label: 'Fußbodenheizung', kategorie: 'Heizung', icon: 'icons/floor-heating.svg', variante: 'floor-heating',
    funktion: 'Heizfläche, Sperrflächen und Heizkreise planen.',
    einsatz: 'Heizung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pipe', label: 'Rohrleitung', kategorie: 'TGA', icon: 'icons/pipe.svg', variante: 'pipe',
    funktion: 'Rohr mit System, Dimension, Höhe und Gefälle zeichnen.',
    einsatz: 'Sanitär, Heizung, Kälte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pump', label: 'Pumpe', kategorie: 'Heizung', icon: 'icons/pump.svg', variante: 'pump',
    funktion: 'Pumpe platzieren und Förderdaten zuweisen.',
    einsatz: 'Hydraulik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'heat-pump', label: 'Wärmepumpe', kategorie: 'Heizung', icon: 'icons/heat-pump.svg', variante: 'heatpump',
    funktion: 'Wärmepumpe platzieren und auslegen.',
    einsatz: 'Wärmeerzeugung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'hydraulic-balance', label: 'Hydraulischer Abgleich', kategorie: 'Heizung', icon: 'icons/hydraulic-balance.svg', variante: 'hydraulic',
    funktion: 'Volumenströme, Druckverluste und Ventile abgleichen.',
    einsatz: 'Heizsystem.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'sanitary', label: 'Sanitäranschluss', kategorie: 'Sanitär', icon: 'icons/sanitary.svg', variante: 'sanitary',
    funktion: 'Wasser- und Abwasseranschlüsse definieren.',
    einsatz: 'Bad, Küche, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'bath', label: 'Badewanne', kategorie: 'Bad', icon: 'icons/bath.svg', variante: 'bath',
    funktion: 'Badewanne mit Bewegungs- und Anschlussflächen platzieren.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'shower', label: 'Dusche', kategorie: 'Bad', icon: 'icons/shower.svg', variante: 'shower',
    funktion: 'Dusche, Rinne und Gefällebereich planen.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'toilet', label: 'WC', kategorie: 'Bad', icon: 'icons/toilet.svg', variante: 'toilet',
    funktion: 'WC mit Vorwand, Abwasser und Bewegungsfläche platzieren.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kitchen', label: 'Küchenplanung', kategorie: 'Küche', icon: 'icons/kitchen.svg', variante: 'kitchen',
    funktion: 'Küchenform und Arbeitszonen anlegen.',
    einsatz: 'Küchenplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'cabinet', label: 'Schrank', kategorie: 'Küche', icon: 'icons/cabinet.svg', variante: 'cabinet',
    funktion: 'Küchenschrank oder Möbelmodul konfigurieren.',
    einsatz: 'Küche und Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'appliance', label: 'Gerät', kategorie: 'Küche', icon: 'icons/appliance.svg', variante: 'appliance',
    funktion: 'Elektro- oder Küchengerät einsetzen.',
    einsatz: 'Küche, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'electric', label: 'Elektroplanung', kategorie: 'Elektro', icon: 'icons/electric.svg', variante: 'electric',
    funktion: 'Elektro-Workspace und Systemfunktionen öffnen.',
    einsatz: 'Elektroplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'socket', label: 'Steckdose', kategorie: 'Elektro', icon: 'icons/socket.svg', variante: 'socket',
    funktion: 'Steckdose mit Typ und Montagehöhe platzieren.',
    einsatz: 'Elektro, Küche, Bad.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'switch', label: 'Schalter', kategorie: 'Elektro', icon: 'icons/switch.svg', variante: 'switch',
    funktion: 'Schalter, Taster oder Dimmer platzieren.',
    einsatz: 'Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'light', label: 'Leuchte', kategorie: 'Elektro', icon: 'icons/light.svg', variante: 'light',
    funktion: 'Leuchte oder Lichtpunkt platzieren.',
    einsatz: 'Elektro und Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'distribution-board', label: 'Verteiler', kategorie: 'Elektro', icon: 'icons/distribution-board.svg', variante: 'panel',
    funktion: 'Elektroverteiler und Stromkreisbelegung konfigurieren.',
    einsatz: 'Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pv-module', label: 'PV-Modul', kategorie: 'PV', icon: 'icons/pv-module.svg', variante: 'pv',
    funktion: 'PV-Modul oder Modulreihe platzieren.',
    einsatz: 'PV-Planung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'battery', label: 'Batteriespeicher', kategorie: 'PV', icon: 'icons/battery.svg', variante: 'battery',
    funktion: 'Speicher platzieren und Kapazität zuweisen.',
    einsatz: 'PV und Energiesystem.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'wallbox', label: 'Wallbox', kategorie: 'PV', icon: 'icons/wallbox.svg', variante: 'wallbox',
    funktion: 'Wallbox mit Stellplatz und Stromkreis platzieren.',
    einsatz: 'Elektro und Mobilität.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'wizard', label: 'Wizard / Assistent', kategorie: 'Workflow', icon: 'icons/wizard.svg', variante: 'wizard',
    funktion: 'Geführten Fachprozess starten oder fortsetzen.',
    einsatz: 'Alle Fachbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'workflow', label: 'Prozessübersicht', kategorie: 'Workflow', icon: 'icons/workflow.svg', variante: 'workflow',
    funktion: 'Abhängige Planungsschritte und Status anzeigen.',
    einsatz: 'Technische Planung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'handoff-package', label: 'Übergabepaket', kategorie: 'Workflow', icon: 'icons/handoff-package.svg', variante: 'package',
    funktion: 'Versioniertes Datenpaket an Fachmodul übergeben.',
    einsatz: 'Heizlast, TGA, Dach, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'approve', label: 'Freigeben', kategorie: 'Workflow', icon: 'icons/approve.svg', variante: 'approve',
    funktion: 'Berechnung, Planung oder Revision freigeben.',
    einsatz: 'Prüfung und Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'comment', label: 'Kommentar', kategorie: 'Zusammenarbeit', icon: 'icons/comment.svg', variante: 'comment',
    funktion: 'Kommentar an Objekt oder Position setzen.',
    einsatz: 'Teamarbeit.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'history', label: 'Historie', kategorie: 'Zusammenarbeit', icon: 'icons/history.svg', variante: 'history',
    funktion: 'Änderungsverlauf eines Objekts oder Projekts anzeigen.',
    einsatz: 'Audit und Revision.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'revision', label: 'Revision', kategorie: 'Zusammenarbeit', icon: 'icons/revision.svg', variante: 'revision',
    funktion: 'Versionierten Planungsstand erzeugen oder vergleichen.',
    einsatz: 'Projektsteuerung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'check', label: 'Prüfen', kategorie: 'Prüfung', icon: 'icons/check.svg', variante: 'check',
    funktion: 'Regel- oder Vollständigkeitsprüfung starten.',
    einsatz: 'Alle Fachbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'warning', label: 'Warnungen', kategorie: 'Prüfung', icon: 'icons/warning.svg', variante: 'warning',
    funktion: 'Warnungen und Abweichungen anzeigen.',
    einsatz: 'Prüfungscenter.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'error', label: 'Fehler', kategorie: 'Prüfung', icon: 'icons/error.svg', variante: 'error',
    funktion: 'Blockierende Fehler anzeigen und bearbeiten.',
    einsatz: 'Prüfungscenter.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'settings', label: 'Einstellungen', kategorie: 'System', icon: 'icons/settings.svg', variante: 'settings',
    funktion: 'Workspace, Toolbar und Benutzeroptionen konfigurieren.',
    einsatz: 'System.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'search', label: 'Suche', kategorie: 'System', icon: 'icons/search.svg', variante: 'search',
    funktion: 'Werkzeuge, Objekte und Dokumente durchsuchen.',
    einsatz: 'Global.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+K' },
  { id: 'command-palette', label: 'Command-Palette', kategorie: 'System', icon: 'icons/command-palette.svg', variante: 'command',
    funktion: 'Alle Befehle und Werkzeuge zentral aufrufen.',
    einsatz: 'Expertenmodus.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+K' },
  { id: 'export', label: 'Exportieren', kategorie: 'System', icon: 'icons/export.svg', variante: 'export',
    funktion: 'Aktuelle Ansicht, Modell oder Daten exportieren.',
    einsatz: 'Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pdf', label: 'PDF / Planblatt', kategorie: 'System', icon: 'icons/pdf.svg', variante: 'pdf',
    funktion: 'Druckfähiges Planblatt oder PDF erzeugen.',
    einsatz: 'Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
];
