/**
 * I2 (AUF-21) — das 110er-Werkzeugpaket als typisierte Daten.
 *
 * **Erzeugt aus** `docs/planner/tool-registry-paket.json` (110 Einträge, Yamas Paket). Als TS-Modul
 * abgelegt und nicht zur Laufzeit aus JSON geladen — genauso wie der bisherige Katalog: die Daten
 * sind damit typgeprüft, im Bundle ohne Ladeschritt und im Diff lesbar.
 *
 * **Feldnamen deutsch**, dem Yama-Entscheid „alles deutsch" folgend (`14e6346`). Die **ids bleiben
 * unverändert aus dem Paket** — sie sind zugleich der Dateiname des Icons
 * (`public/hausplaner/icons/tools/<id>.svg`, I1 `7bbf9ff`). Eine Eindeutschung der ids wäre eine
 * eigene Entscheidung mit Wirkung auf 110 Dateinamen; sie steht im Bericht als Frage an Yama.
 *
 * Zwei Felder tragen mehr als Beiwerk und sind der Grund, warum das Paket überhaupt hier landet:
 * `anheftbar` (canPin) ist der Werkzeug-Zustand „angeheftet", `prioritaet` bildet ab, was die
 * Zonen-Kuratierung heute von Hand pflegt. **Verwendet werden sie in I3, nicht hier.**
 */

/** Ein Werkzeug aus Yamas Paket — Rohform, noch nicht auf `ToolDefinition` abgebildet. */
export interface PaketWerkzeug {
  id: string;
  label: string;
  kategorie: string;
  icon: string;
  variante: string;
  funktion: string;
  einsatz: string;
  ansichten: readonly string[];
  prioritaet: 'primary' | 'secondary';
  anheftbar: boolean;
  shortcut?: string;
}

/** Die 110 Fach-Werkzeuge. Reihenfolge = Paket-Reihenfolge (Kategorie-Gruppen). */
export const PAKET_WERKZEUGE: readonly PaketWerkzeug[] = [
  { id: 'direktauswahl', label: 'Direktauswahl', kategorie: 'Auswahl', icon: 'icons/direktauswahl.svg', variante: 'cursor-direct',
    funktion: 'Punkte, Kanten oder Teilflächen auswählen.',
    einsatz: 'Geometrische Detailkorrektur.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'A' },
  { id: 'rechteckauswahl', label: 'Rechteckauswahl', kategorie: 'Auswahl', icon: 'icons/rechteckauswahl.svg', variante: 'box-select',
    funktion: 'Mehrere Objekte mit Auswahlrahmen erfassen.',
    einsatz: 'Grundriss, Fassaden, technische Netze.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'lassoauswahl', label: 'Lassoauswahl', kategorie: 'Auswahl', icon: 'icons/lassoauswahl.svg', variante: 'lasso',
    funktion: 'Unregelmäßige Objektgruppen auswählen.',
    einsatz: 'Komplexe Grundrisse und TGA-Bereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'verschieben', label: 'Verschieben', kategorie: 'Bearbeiten', icon: 'icons/verschieben.svg', variante: 'move',
    funktion: 'Objekte entlang X, Y oder Z verschieben.',
    einsatz: 'Alle bearbeitbaren Fachobjekte.',
    ansichten: ['2D', '3D'], prioritaet: 'primary', anheftbar: true, shortcut: 'G' },
  { id: 'drehen', label: 'Drehen', kategorie: 'Bearbeiten', icon: 'icons/drehen.svg', variante: 'rotate',
    funktion: 'Objekte um einen Bezugspunkt drehen.',
    einsatz: 'Möbel, Bauteile, Referenzen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'R' },
  { id: 'skalieren', label: 'Skalieren', kategorie: 'Bearbeiten', icon: 'icons/skalieren.svg', variante: 'scale',
    funktion: 'Freie Geometrie proportional oder achsweise skalieren.',
    einsatz: 'Importe, Referenzen und freie Objekte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'S' },
  { id: 'horizontal-spiegeln', label: 'Horizontal spiegeln', kategorie: 'Bearbeiten', icon: 'icons/horizontal-spiegeln.svg', variante: 'mirror-h',
    funktion: 'Objekt an vertikaler Achse spiegeln.',
    einsatz: 'Grundrisse, Türen, Fensterteilungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'vertikal-spiegeln', label: 'Vertikal spiegeln', kategorie: 'Bearbeiten', icon: 'icons/vertikal-spiegeln.svg', variante: 'mirror-v',
    funktion: 'Objekt an horizontaler Achse spiegeln.',
    einsatz: 'Dachkonturen, Symmetrien.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kopieren', label: 'Kopieren', kategorie: 'Bearbeiten', icon: 'icons/kopieren.svg', variante: 'copy',
    funktion: 'Auswahl in Zwischenablage kopieren.',
    einsatz: 'Alle Workspaces.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+C' },
  { id: 'sperren', label: 'Sperren', kategorie: 'Bearbeiten', icon: 'icons/sperren.svg', variante: 'lock',
    funktion: 'Objekt vor Änderungen schützen.',
    einsatz: 'Referenzen, freigegebene Bauteile.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'entsperren', label: 'Entsperren', kategorie: 'Bearbeiten', icon: 'icons/entsperren.svg', variante: 'unlock',
    funktion: 'Bearbeitung gesperrter Objekte zulassen.',
    einsatz: 'Berechtigte Nutzer.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'einblenden', label: 'Einblenden', kategorie: 'Bearbeiten', icon: 'icons/einblenden.svg', variante: 'eye',
    funktion: 'Ausgeblendete Objekte sichtbar machen.',
    einsatz: 'Layer- und Modellsteuerung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'ausblenden', label: 'Ausblenden', kategorie: 'Bearbeiten', icon: 'icons/ausblenden.svg', variante: 'eye-off',
    funktion: 'Objekte temporär ausblenden.',
    einsatz: 'Koordination und Modellprüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'gruppieren', label: 'Gruppieren', kategorie: 'Bearbeiten', icon: 'icons/gruppieren.svg', variante: 'group',
    funktion: 'Mehrere Objekte als Gruppe behandeln.',
    einsatz: 'Möbel, Symbole, technische Komponenten.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'ausrichten', label: 'Ausrichten', kategorie: 'Bearbeiten', icon: 'icons/ausrichten.svg', variante: 'align',
    funktion: 'Objekte an Kante, Achse oder Mitte ausrichten.',
    einsatz: 'Innenraum, Fassaden, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'verteilen', label: 'Verteilen', kategorie: 'Bearbeiten', icon: 'icons/verteilen.svg', variante: 'distribute',
    funktion: 'Objekte gleichmäßig verteilen.',
    einsatz: 'Fenster, Leuchten, PV-Module.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'linie', label: 'Linie', kategorie: 'Zeichnen', icon: 'icons/linie.svg', variante: 'line',
    funktion: 'Gerade Linie zwischen zwei Punkten zeichnen.',
    einsatz: 'Hilfsgeometrie und technische Zeichnung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'L' },
  { id: 'polylinie', label: 'Polylinie', kategorie: 'Zeichnen', icon: 'icons/polylinie.svg', variante: 'polyline',
    funktion: 'Zusammenhängende Liniensegmente zeichnen.',
    einsatz: 'Konturen, Leitungswege und Grundstücke.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'rechteck', label: 'Rechteck', kategorie: 'Zeichnen', icon: 'icons/rechteck.svg', variante: 'rectangle',
    funktion: 'Rechteckige Kontur erzeugen.',
    einsatz: 'Räume, Öffnungen und Flächen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'polygon', label: 'Polygon', kategorie: 'Zeichnen', icon: 'icons/polygon.svg', variante: 'polygon',
    funktion: 'Freie geschlossene Kontur zeichnen.',
    einsatz: 'Dächer, Grundstücke und Zonen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kreis', label: 'Kreis', kategorie: 'Zeichnen', icon: 'icons/kreis.svg', variante: 'circle',
    funktion: 'Kreis über Mittelpunkt und Radius erzeugen.',
    einsatz: 'Runde Bauteile und Schächte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'bogen', label: 'Bogen', kategorie: 'Zeichnen', icon: 'icons/bogen.svg', variante: 'arc',
    funktion: 'Kreisbogen oder tangentialen Bogen erzeugen.',
    einsatz: 'Bogenwände und Leitungsführung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'trimmen', label: 'Trimmen', kategorie: 'CAD', icon: 'icons/trimmen.svg', variante: 'trim',
    funktion: 'Überstehende Linien an Begrenzungen abschneiden.',
    einsatz: 'Grundriss- und Detailkorrektur.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'verlaengern', label: 'Verlängern', kategorie: 'CAD', icon: 'icons/verlaengern.svg', variante: 'extend',
    funktion: 'Linien bis zu einer Begrenzung verlängern.',
    einsatz: 'Wände, Achsen, Leitungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'versatz', label: 'Versatz', kategorie: 'CAD', icon: 'icons/versatz.svg', variante: 'offset',
    funktion: 'Parallele Kopie mit festem Abstand erzeugen.',
    einsatz: 'Wände, Installationszonen, Dachüberstand.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'teilen', label: 'Teilen', kategorie: 'CAD', icon: 'icons/teilen.svg', variante: 'split',
    funktion: 'Linie oder Fachobjekt an einem Punkt teilen.',
    einsatz: 'Wände, Leitungen, Dachflächen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'verbinden', label: 'Verbinden', kategorie: 'CAD', icon: 'icons/verbinden.svg', variante: 'join',
    funktion: 'Getrennte Segmente oder Objekte verbinden.',
    einsatz: 'Konturen, Leitungsnetze.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'raum', label: 'Raum', kategorie: 'Architektur', icon: 'icons/raum.svg', variante: 'room',
    funktion: 'Geschlossene Raumkontur erkennen oder erzeugen.',
    einsatz: 'Grundriss, Heizlast, Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'gaube', label: 'Gaube', kategorie: 'Architektur', icon: 'icons/gaube.svg', variante: 'dormer',
    funktion: 'Gaube mit Dachöffnung und Seitenwänden einsetzen.',
    einsatz: 'Dachplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'dachfenster', label: 'Dachfenster', kategorie: 'Architektur', icon: 'icons/dachfenster.svg', variante: 'roof-window',
    funktion: 'Dachfenster in geneigter Dachfläche platzieren.',
    einsatz: 'Dachplanung, Heizlast.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'stuetze', label: 'Stütze', kategorie: 'Architektur', icon: 'icons/stuetze.svg', variante: 'column',
    funktion: 'Tragende oder gestalterische Stütze setzen.',
    einsatz: 'Architektur und Tragwerk.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'unterzug', label: 'Unterzug / Träger', kategorie: 'Architektur', icon: 'icons/unterzug.svg', variante: 'beam',
    funktion: 'Horizontalen Träger oder Unterzug erzeugen.',
    einsatz: 'Tragwerk und Kollisionsprüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'oeffnung', label: 'Öffnung', kategorie: 'Architektur', icon: 'icons/oeffnung.svg', variante: 'opening',
    funktion: 'Durchbruch in Wand, Decke, Boden oder Dach erzeugen.',
    einsatz: 'Architektur und TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'boden', label: 'Boden', kategorie: 'Architektur', icon: 'icons/boden.svg', variante: 'floor',
    funktion: 'Bodenfläche und Bodenaufbau erzeugen.',
    einsatz: 'Innenraum, Bauphysik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'schnitt', label: 'Schnitt', kategorie: 'Architektur', icon: 'icons/schnitt.svg', variante: 'section',
    funktion: 'Schnittlinie und abgeleitete Schnittansicht erzeugen.',
    einsatz: 'Treppen, Dächer, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'aufriss', label: 'Fassade / Ansicht', kategorie: 'Architektur', icon: 'icons/aufriss.svg', variante: 'elevation',
    funktion: 'Orthogonale Gebäudeansicht erzeugen.',
    einsatz: 'Fassade, Fenster, Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'vergroessern', label: 'Vergrößern', kategorie: 'Ansicht', icon: 'icons/vergroessern.svg', variante: 'zoom-in',
    funktion: 'Ansicht schrittweise vergrößern.',
    einsatz: 'Detailbearbeitung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: '+' },
  { id: 'verkleinern', label: 'Verkleinern', kategorie: 'Ansicht', icon: 'icons/verkleinern.svg', variante: 'zoom-out',
    funktion: 'Ansicht schrittweise verkleinern.',
    einsatz: 'Modellübersicht.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: '-' },
  { id: 'alles-anzeigen', label: 'Alles anzeigen', kategorie: 'Ansicht', icon: 'icons/alles-anzeigen.svg', variante: 'fit',
    funktion: 'Modell oder Referenz vollständig einpassen.',
    einsatz: 'Alle Workspaces.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Shift+F' },
  { id: 'hand', label: 'Pan / Hand', kategorie: 'Ansicht', icon: 'icons/hand.svg', variante: 'pan',
    funktion: 'Canvas verschieben, ohne Geometrie zu ändern.',
    einsatz: '2D und 3D.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Space' },
  { id: 'umkreisen', label: 'Orbit', kategorie: 'Ansicht', icon: 'icons/umkreisen.svg', variante: 'orbit',
    funktion: '3D-Kamera um Fokuspunkt drehen.',
    einsatz: '3D-Ansicht.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'raster', label: 'Raster', kategorie: 'Ansicht', icon: 'icons/raster.svg', variante: 'grid',
    funktion: 'Zeichenraster ein- oder ausblenden.',
    einsatz: '2D, Import, Grundriss.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'G' },
  { id: 'fang', label: 'Fang', kategorie: 'Ansicht', icon: 'icons/fang.svg', variante: 'snap',
    funktion: 'Fang an Raster, Kanten, End- und Schnittpunkten.',
    einsatz: 'Präzises Zeichnen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'S' },
  { id: 'distanz-messen', label: 'Distanz messen', kategorie: 'Messen', icon: 'icons/distanz-messen.svg', variante: 'measure',
    funktion: 'Temporäre Distanz zwischen zwei Punkten messen.',
    einsatz: 'Alle Planungsbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'M' },
  { id: 'bemassen', label: 'Bemaßen', kategorie: 'Messen', icon: 'icons/bemassen.svg', variante: 'dimension',
    funktion: 'Persistente technische Maßlinie erzeugen.',
    einsatz: '2D, Schnitt, Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'winkel-messen', label: 'Winkel messen', kategorie: 'Messen', icon: 'icons/winkel-messen.svg', variante: 'angle',
    funktion: 'Winkel zwischen Linien oder Flächen messen.',
    einsatz: 'Dach, Treppe, Leitungen.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'flaeche-messen', label: 'Fläche messen', kategorie: 'Messen', icon: 'icons/flaeche-messen.svg', variante: 'area',
    funktion: 'Geschlossene Fläche ermitteln.',
    einsatz: 'Räume, Fassaden, Dächer.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'volumen-messen', label: 'Volumen messen', kategorie: 'Messen', icon: 'icons/volumen-messen.svg', variante: 'volume',
    funktion: 'Körper- oder Raumvolumen ermitteln.',
    einsatz: 'Heizlast, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'datei-importieren', label: 'Datei importieren', kategorie: 'Import', icon: 'icons/datei-importieren.svg', variante: 'import',
    funktion: 'PDF, Bild, DWG, DXF, IFC oder SVG laden.',
    einsatz: 'Import & Nachzeichnen.',
    ansichten: ['2D'], prioritaet: 'primary', anheftbar: true, shortcut: 'I' },
  { id: 'bild-importieren', label: 'Bild importieren', kategorie: 'Import', icon: 'icons/bild-importieren.svg', variante: 'image',
    funktion: 'Rasterbild oder Scan als Referenz laden.',
    einsatz: 'Bestandsgrundrisse.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kalibrieren', label: 'Kalibrieren', kategorie: 'Import', icon: 'icons/kalibrieren.svg', variante: 'calibrate',
    funktion: 'Bildmaßstab über bekannte Strecke bestimmen.',
    einsatz: 'Grundrissimport.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'beschneiden', label: 'Beschneiden', kategorie: 'Import', icon: 'icons/beschneiden.svg', variante: 'crop',
    funktion: 'Referenz auf relevanten Bereich beschneiden.',
    einsatz: 'PDF und Bild.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'nordrichtung-setzen', label: 'Nordrichtung setzen', kategorie: 'Import', icon: 'icons/nordrichtung-setzen.svg', variante: 'north',
    funktion: 'Nordrichtung und Gebäudebezug festlegen.',
    einsatz: 'Import, PV, Verschattung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'grundriss-erkennen', label: 'Grundriss erkennen', kategorie: 'Import', icon: 'icons/grundriss-erkennen.svg', variante: 'detect',
    funktion: 'Wände, Räume, Fenster, Türen und Maße erkennen.',
    einsatz: 'KI-/Regelerkennung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'ki-assistent', label: 'KI-Assistent', kategorie: 'Import', icon: 'icons/ki-assistent.svg', variante: 'ai',
    funktion: 'Vorschläge, Erkennung und Korrektur unterstützen.',
    einsatz: 'Import, Planung, Prüfung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'erkennung-bestaetigen', label: 'Erkennung bestätigen', kategorie: 'Import', icon: 'icons/erkennung-bestaetigen.svg', variante: 'check',
    funktion: 'Erkanntes Objekt als Fachobjekt übernehmen.',
    einsatz: 'Review-Modus.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'material-zuweisen', label: 'Material zuweisen', kategorie: 'Material', icon: 'icons/material-zuweisen.svg', variante: 'material',
    funktion: 'Technisches oder sichtbares Material zuordnen.',
    einsatz: 'Fassade, Fenster, Türen, Dach.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'textur', label: 'Textur / PBR', kategorie: 'Material', icon: 'icons/textur.svg', variante: 'texture',
    funktion: 'PBR-Texturensatz und Mapping wählen.',
    einsatz: '3D-Darstellung und Rendering.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'material-aufnehmen', label: 'Material aufnehmen', kategorie: 'Material', icon: 'icons/material-aufnehmen.svg', variante: 'paint',
    funktion: 'Material von Objekt übernehmen und übertragen.',
    einsatz: 'Innenraum und Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'fassadensystem', label: 'Fassadensystem', kategorie: 'Fassade', icon: 'icons/fassadensystem.svg', variante: 'facade',
    funktion: 'Putz, Klinker, Holz oder Plattensystem zuweisen.',
    einsatz: 'Fassadenplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'klinker', label: 'Klinker / Verband', kategorie: 'Fassade', icon: 'icons/klinker.svg', variante: 'brick',
    funktion: 'Klinkerformat, Fuge und Verband konfigurieren.',
    einsatz: 'Fassade.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'daemmung', label: 'Dämmung', kategorie: 'Bauphysik', icon: 'icons/daemmung.svg', variante: 'insulation',
    funktion: 'Dämmstoff und Dämmstärke festlegen.',
    einsatz: 'Wand, Dach, Decke, Boden.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'u-wert', label: 'U-Wert', kategorie: 'Bauphysik', icon: 'icons/u-wert.svg', variante: 'uvalue',
    funktion: 'U-Wert berechnen, prüfen oder überschreiben.',
    einsatz: 'Heizlast und Bauphysik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'thermische-huelle', label: 'Thermische Hülle', kategorie: 'Bauphysik', icon: 'icons/thermische-huelle.svg', variante: 'thermal',
    funktion: 'Wärmeübertragende Gebäudehülle markieren.',
    einsatz: 'Heizlast-Datencheck.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'lueftung', label: 'Lüftung', kategorie: 'Bauphysik', icon: 'icons/lueftung.svg', variante: 'ventilation',
    funktion: 'Lüftungszonen und Luftwechsel definieren.',
    einsatz: 'Heizlast und TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'heizkoerper', label: 'Heizkörper', kategorie: 'Heizung', icon: 'icons/heizkoerper.svg', variante: 'radiator',
    funktion: 'Heizkörper platzieren und auf Raumheizlast auslegen.',
    einsatz: 'Heizung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'fussbodenheizung', label: 'Fußbodenheizung', kategorie: 'Heizung', icon: 'icons/fussbodenheizung.svg', variante: 'floor-heating',
    funktion: 'Heizfläche, Sperrflächen und Heizkreise planen.',
    einsatz: 'Heizung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'rohrleitung', label: 'Rohrleitung', kategorie: 'TGA', icon: 'icons/rohrleitung.svg', variante: 'pipe',
    funktion: 'Rohr mit System, Dimension, Höhe und Gefälle zeichnen.',
    einsatz: 'Sanitär, Heizung, Kälte.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pumpe', label: 'Pumpe', kategorie: 'Heizung', icon: 'icons/pumpe.svg', variante: 'pump',
    funktion: 'Pumpe platzieren und Förderdaten zuweisen.',
    einsatz: 'Hydraulik.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'waermepumpe', label: 'Wärmepumpe', kategorie: 'Heizung', icon: 'icons/waermepumpe.svg', variante: 'heatpump',
    funktion: 'Wärmepumpe platzieren und auslegen.',
    einsatz: 'Wärmeerzeugung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'hydraulischer-abgleich', label: 'Hydraulischer Abgleich', kategorie: 'Heizung', icon: 'icons/hydraulischer-abgleich.svg', variante: 'hydraulic',
    funktion: 'Volumenströme, Druckverluste und Ventile abgleichen.',
    einsatz: 'Heizsystem.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'sanitaeranschluss', label: 'Sanitäranschluss', kategorie: 'Sanitär', icon: 'icons/sanitaeranschluss.svg', variante: 'sanitary',
    funktion: 'Wasser- und Abwasseranschlüsse definieren.',
    einsatz: 'Bad, Küche, TGA.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'badewanne', label: 'Badewanne', kategorie: 'Bad', icon: 'icons/badewanne.svg', variante: 'bath',
    funktion: 'Badewanne mit Bewegungs- und Anschlussflächen platzieren.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'dusche', label: 'Dusche', kategorie: 'Bad', icon: 'icons/dusche.svg', variante: 'shower',
    funktion: 'Dusche, Rinne und Gefällebereich planen.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'wc', label: 'WC', kategorie: 'Bad', icon: 'icons/wc.svg', variante: 'toilet',
    funktion: 'WC mit Vorwand, Abwasser und Bewegungsfläche platzieren.',
    einsatz: 'Badplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kuechenplanung', label: 'Küchenplanung', kategorie: 'Küche', icon: 'icons/kuechenplanung.svg', variante: 'kitchen',
    funktion: 'Küchenform und Arbeitszonen anlegen.',
    einsatz: 'Küchenplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'schrank', label: 'Schrank', kategorie: 'Küche', icon: 'icons/schrank.svg', variante: 'cabinet',
    funktion: 'Küchenschrank oder Möbelmodul konfigurieren.',
    einsatz: 'Küche und Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'geraet', label: 'Gerät', kategorie: 'Küche', icon: 'icons/geraet.svg', variante: 'appliance',
    funktion: 'Elektro- oder Küchengerät einsetzen.',
    einsatz: 'Küche, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'elektroplanung', label: 'Elektroplanung', kategorie: 'Elektro', icon: 'icons/elektroplanung.svg', variante: 'electric',
    funktion: 'Elektro-Workspace und Systemfunktionen öffnen.',
    einsatz: 'Elektroplanung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'steckdose', label: 'Steckdose', kategorie: 'Elektro', icon: 'icons/steckdose.svg', variante: 'socket',
    funktion: 'Steckdose mit Typ und Montagehöhe platzieren.',
    einsatz: 'Elektro, Küche, Bad.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'schalter', label: 'Schalter', kategorie: 'Elektro', icon: 'icons/schalter.svg', variante: 'switch',
    funktion: 'Schalter, Taster oder Dimmer platzieren.',
    einsatz: 'Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'leuchte', label: 'Leuchte', kategorie: 'Elektro', icon: 'icons/leuchte.svg', variante: 'light',
    funktion: 'Leuchte oder Lichtpunkt platzieren.',
    einsatz: 'Elektro und Innenraum.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'verteiler', label: 'Verteiler', kategorie: 'Elektro', icon: 'icons/verteiler.svg', variante: 'panel',
    funktion: 'Elektroverteiler und Stromkreisbelegung konfigurieren.',
    einsatz: 'Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pv-modul', label: 'PV-Modul', kategorie: 'PV', icon: 'icons/pv-modul.svg', variante: 'pv',
    funktion: 'PV-Modul oder Modulreihe platzieren.',
    einsatz: 'PV-Planung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'batteriespeicher', label: 'Batteriespeicher', kategorie: 'PV', icon: 'icons/batteriespeicher.svg', variante: 'battery',
    funktion: 'Speicher platzieren und Kapazität zuweisen.',
    einsatz: 'PV und Energiesystem.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'wallbox', label: 'Wallbox', kategorie: 'PV', icon: 'icons/wallbox.svg', variante: 'wallbox',
    funktion: 'Wallbox mit Stellplatz und Stromkreis platzieren.',
    einsatz: 'Elektro und Mobilität.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'assistent', label: 'Wizard / Assistent', kategorie: 'Workflow', icon: 'icons/assistent.svg', variante: 'wizard',
    funktion: 'Geführten Fachprozess starten oder fortsetzen.',
    einsatz: 'Alle Fachbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'prozessuebersicht', label: 'Prozessübersicht', kategorie: 'Workflow', icon: 'icons/prozessuebersicht.svg', variante: 'workflow',
    funktion: 'Abhängige Planungsschritte und Status anzeigen.',
    einsatz: 'Technische Planung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'uebergabepaket', label: 'Übergabepaket', kategorie: 'Workflow', icon: 'icons/uebergabepaket.svg', variante: 'package',
    funktion: 'Versioniertes Datenpaket an Fachmodul übergeben.',
    einsatz: 'Heizlast, TGA, Dach, Elektro.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'freigeben', label: 'Freigeben', kategorie: 'Workflow', icon: 'icons/freigeben.svg', variante: 'approve',
    funktion: 'Berechnung, Planung oder Revision freigeben.',
    einsatz: 'Prüfung und Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'kommentar', label: 'Kommentar', kategorie: 'Zusammenarbeit', icon: 'icons/kommentar.svg', variante: 'comment',
    funktion: 'Kommentar an Objekt oder Position setzen.',
    einsatz: 'Teamarbeit.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'historie', label: 'Historie', kategorie: 'Zusammenarbeit', icon: 'icons/historie.svg', variante: 'history',
    funktion: 'Änderungsverlauf eines Objekts oder Projekts anzeigen.',
    einsatz: 'Audit und Revision.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'revision', label: 'Revision', kategorie: 'Zusammenarbeit', icon: 'icons/revision.svg', variante: 'revision',
    funktion: 'Versionierten Planungsstand erzeugen oder vergleichen.',
    einsatz: 'Projektsteuerung.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pruefen', label: 'Prüfen', kategorie: 'Prüfung', icon: 'icons/pruefen.svg', variante: 'check',
    funktion: 'Regel- oder Vollständigkeitsprüfung starten.',
    einsatz: 'Alle Fachbereiche.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'warnungen', label: 'Warnungen', kategorie: 'Prüfung', icon: 'icons/warnungen.svg', variante: 'warning',
    funktion: 'Warnungen und Abweichungen anzeigen.',
    einsatz: 'Prüfungscenter.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'fehler', label: 'Fehler', kategorie: 'Prüfung', icon: 'icons/fehler.svg', variante: 'error',
    funktion: 'Blockierende Fehler anzeigen und bearbeiten.',
    einsatz: 'Prüfungscenter.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'einstellungen', label: 'Einstellungen', kategorie: 'System', icon: 'icons/einstellungen.svg', variante: 'settings',
    funktion: 'Workspace, Toolbar und Benutzeroptionen konfigurieren.',
    einsatz: 'System.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'suche', label: 'Suche', kategorie: 'System', icon: 'icons/suche.svg', variante: 'search',
    funktion: 'Werkzeuge, Objekte und Dokumente durchsuchen.',
    einsatz: 'Global.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+K' },
  { id: 'befehlspalette', label: 'Command-Palette', kategorie: 'System', icon: 'icons/befehlspalette.svg', variante: 'command',
    funktion: 'Alle Befehle und Werkzeuge zentral aufrufen.',
    einsatz: 'Expertenmodus.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true, shortcut: 'Ctrl/Cmd+K' },
  { id: 'exportieren', label: 'Exportieren', kategorie: 'System', icon: 'icons/exportieren.svg', variante: 'export',
    funktion: 'Aktuelle Ansicht, Modell oder Daten exportieren.',
    einsatz: 'Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
  { id: 'pdf', label: 'PDF / Planblatt', kategorie: 'System', icon: 'icons/pdf.svg', variante: 'pdf',
    funktion: 'Druckfähiges Planblatt oder PDF erzeugen.',
    einsatz: 'Dokumentation.',
    ansichten: ['2D', '3D'], prioritaet: 'secondary', anheftbar: true },
];
