[Interface]
PrivateKey = ODzd5aaC36zI78N0uib5di+CkiXuWWENHgLACbFv8nE=
Address = 192.168.10.203/24,fdb1:1b1b:a786::203/64
DNS = 192.168.10.1,fdb1:1b1b:a786::b2f2:8ff:fe19:6318,192.168.8.1
DNS = fritz.box

[Peer]
PublicKey = 0nzuoAmnG8t0v+ZZPKuUPydlJTKFt+I2P7x7/OJKC2I=
PresharedKey = xt+PFqiATLtkQNe+xCXNrMcJgUnELK/uOCFwhDpww7A=
AllowedIPs = 192.168.10.0/24,192.168.8.0/24,0.0.0.0/0,fdb1:1b1b:a786::/64,::/0
Endpoint = rpqj9dxo07cl48en.myfritz.net:52356
PersistentKeepalive = 25
