@extends('admin.layouts.app')
@section('title', 'Maschinenbestand')


@php
    // Safe fallbacks: prevents "Undefined variable" errors if an old controller still opens this Blade.
    $machineStatuses = $machineStatuses ?? [
        'active' => 'Aktiv',
        'in_service' => 'Im Service',
        'repair' => 'Reparatur',
        'inspection_due' => 'TÜV fällig',
        'inactive' => 'Inaktiv',
    ];

    $serviceStatuses = $serviceStatuses ?? [
        'open' => 'Offen',
        'in_progress' => 'In Bearbeitung',
        'completed' => 'Abgeschlossen',
        'cancelled' => 'Abgebrochen',
    ];

    $installmentStatuses = $installmentStatuses ?? [
        'open' => 'Offen',
        'paid' => 'Bezahlt',
        'overdue' => 'Überfällig',
        'cancelled' => 'Storniert',
    ];

    $branches = $branches ?? collect();
    $departments = $departments ?? collect();
    $employees = $employees ?? collect();
    $article_groups = $article_groups ?? collect();
    $selectedMachineId = $selectedMachineId ?? request('machine_id');
    $openServices = $openServices ?? request()->boolean('open_services');
@endphp

@section('style')
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/forms/select/select2.min.css') }}">
    <style>
      :root{
        --oc-bg:#f3f4f6;--oc-card:#fff;--oc-text:#1f2937;--oc-muted:#6b7280;--oc-border:#e5e7eb;
        --oc-primary:var(--sa-accent);--oc-primary-hover:var(--sa-accent-hover);--oc-primary-light:var(--sa-accent-light);--oc-blue:var(--sa-accent);--oc-blue-light:#eff6ff;
        --oc-success:#10b981;--oc-success-light:#ecfdf5;--oc-warning:#f59e0b;--oc-warning-light:#fffbeb;--oc-danger:#ef4444;--oc-danger-light:#fef2f2;
        --oc-shadow-sm:0 1px 2px 0 rgb(0 0 0 / .05);--oc-shadow:0 10px 25px -10px rgb(0 0 0 / .25),0 4px 8px -4px rgb(0 0 0 / .12);
        --oc-radius:14px;--oc-transition:all .2s ease-in-out;
      }
      .oc-wrap{font-family:Inter,system-ui,-apple-system,sans-serif;color:var(--oc-text);padding:1rem;}
      .oc-titlebar{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;margin-bottom:16px;flex-wrap:wrap;}
      .oc-title{font-size:26px;font-weight:900;letter-spacing:-.025em;color:#111827;}
      .oc-sub{font-size:14px;color:var(--oc-muted);margin-top:4px;}
      .oc-breadcrumb{display:flex;align-items:center;gap:8px;margin-top:10px;font-size:13px;color:var(--oc-muted);flex-wrap:wrap;}
      .oc-breadcrumb a{color:var(--oc-muted);font-weight:800;text-decoration:none}.oc-breadcrumb a:hover{color:#111827}.oc-breadcrumb .current{font-weight:900;color:#111827;}
      .oc-btn{background:var(--oc-primary);color:#fff;border:none;padding:10px 16px;border-radius:10px;font-weight:900;cursor:pointer;transition:var(--oc-transition);display:inline-flex;align-items:center;gap:8px;text-decoration:none;line-height:1.1;}
      .oc-btn:hover{background:var(--oc-primary-hover);color:#fff;text-decoration:none}.oc-btn:disabled{opacity:.55;cursor:not-allowed;}
      .oc-btn-soft{background:#fff;color:var(--oc-text);border:1px solid var(--oc-border);padding:10px 14px;border-radius:10px;font-weight:800;cursor:pointer;transition:var(--oc-transition);display:inline-flex;align-items:center;gap:8px;text-decoration:none;}
      .oc-btn-soft:hover{background:#f9fafb;color:#111827;text-decoration:none}.oc-btn-soft.active{border-color:var(--oc-primary);background:var(--oc-primary-light);color:#4d7c0f;}
      .oc-btn-ic{width:36px;height:36px;border-radius:8px;border:1px solid var(--oc-border);background:#fff;display:inline-flex;align-items:center;justify-content:center;color:var(--oc-muted);cursor:pointer;transition:var(--oc-transition);text-decoration:none;}
      .oc-btn-ic:hover{background:#f9fafb;color:#111827;border-color:#d1d5db;text-decoration:none}.oc-btn-ic.primary{color:var(--oc-primary);background:var(--oc-primary-light);border-color:var(--oc-primary-light)}.oc-btn-ic.success{color:var(--oc-success);background:var(--oc-success-light);border-color:#c7f2df}.oc-btn-ic.warning{color:#d97706;background:var(--oc-warning-light);border-color:#fde7b0}.oc-btn-ic.danger{color:var(--oc-danger);background:var(--oc-danger-light);border-color:rgba(239,68,68,.18)}
      .oc-analytics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px;}@media(max-width:1200px){.oc-analytics{grid-template-columns:repeat(2,minmax(0,1fr));}}@media(max-width:700px){.oc-analytics{grid-template-columns:1fr;}}
      .oc-stat{background:var(--oc-card);border:1px solid var(--oc-border);border-radius:16px;padding:16px;box-shadow:var(--oc-shadow-sm);display:flex;align-items:center;gap:12px;min-height:92px;}
      .oc-stat-icon{width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;flex:0 0 auto}.oc-stat-icon.total{background:var(--oc-blue-light);color:var(--oc-blue)}.oc-stat-icon.good{background:var(--oc-success-light);color:var(--oc-success)}.oc-stat-icon.warn{background:var(--oc-warning-light);color:#d97706}.oc-stat-icon.bad{background:var(--oc-danger-light);color:var(--oc-danger)}.oc-stat-icon.gray{background:#f3f4f6;color:#6b7280;}
      .oc-stat-label{font-size:11px;font-weight:900;color:var(--oc-muted);text-transform:uppercase;letter-spacing:.06em}.oc-stat-value{font-size:24px;font-weight:900;color:#111827;line-height:1.1;margin-top:4px}.oc-stat-sub{font-size:12px;color:var(--oc-muted);margin-top:4px;}
      .oc-toolbar{background:#fff;border:1px solid var(--oc-border);border-radius:var(--oc-radius);padding:14px 16px;display:flex;flex-wrap:wrap;gap:14px;align-items:flex-end;justify-content:space-between;margin-bottom:16px;box-shadow:var(--oc-shadow-sm);}
      .oc-toolbar-left,.oc-toolbar-right{display:flex;align-items:flex-end;gap:12px;flex-wrap:wrap}.oc-toolbar-left{flex:1}.oc-filter-block{display:flex;flex-direction:column;gap:6px;min-width:170px}.oc-filter-block.search{flex:1;min-width:280px}.oc-filter-label{font-size:11px;font-weight:900;color:var(--oc-muted);text-transform:uppercase;letter-spacing:.06em;}
      .oc-input{background:#f9fafb;border:1px solid var(--oc-border);border-radius:8px;padding:10px 12px;font-size:14px;outline:none;transition:var(--oc-transition);width:100%;}.oc-input.search{padding-left:36px;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%239ca3af' stroke-width='2'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z' /%3E%3C/svg%3E");background-repeat:no-repeat;background-position:10px center;background-size:16px;}.oc-input:focus{background:#fff;border-color:var(--oc-primary);box-shadow:0 0 0 3px var(--oc-primary-light);}
      .oc-card{background:#fff;border:1px solid var(--oc-border);border-radius:16px;box-shadow:var(--oc-shadow-sm);overflow:hidden;position:relative;}
      .oc-list-head{display:grid;grid-template-columns:70px minmax(240px,1.35fr) minmax(160px,.9fr) minmax(160px,.9fr) minmax(130px,.7fr) minmax(150px,.8fr) 250px;gap:14px;align-items:center;padding:16px 16px 10px;color:var(--oc-muted);font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.06em}@media(max-width:1280px){.oc-list-head{display:none}}
      .oc-list{display:flex;flex-direction:column;gap:12px;padding:0 0 16px}.oc-item{background:#fff;border:1px solid var(--oc-border);border-radius:var(--oc-radius);transition:var(--oc-transition);overflow:hidden;margin:0 16px}.oc-item:hover{border-color:var(--oc-primary);box-shadow:var(--oc-shadow)}
      .oc-item-row{padding:16px;display:grid;gap:16px;align-items:center;grid-template-columns:70px minmax(240px,1.35fr) minmax(160px,.9fr) minmax(160px,.9fr) minmax(130px,.7fr) minmax(150px,.8fr) 250px}@media(max-width:1280px){.oc-item-row{grid-template-columns:1fr}}
      .oc-cell{min-width:0}.oc-cell-title{font-size:11px;font-weight:900;color:var(--oc-muted);text-transform:uppercase;margin-bottom:4px;display:none}@media(max-width:1280px){.oc-cell-title{display:block}}
      .oc-id-badge{display:inline-flex;align-items:center;justify-content:center;min-width:54px;height:36px;padding:0 12px;border-radius:10px;background:var(--oc-blue-light);color:var(--oc-blue);font-size:13px;font-weight:900;}
      .oc-main{display:flex;gap:12px;align-items:center;min-width:0}.oc-thumb{width:54px;height:54px;border-radius:14px;border:1px solid var(--oc-border);background:#fff;object-fit:cover;padding:3px;flex:0 0 auto}.oc-avatar{width:54px;height:54px;border-radius:14px;background:var(--oc-primary-light);color:#4d7c0f;font-weight:900;display:flex;align-items:center;justify-content:center;flex:0 0 auto}.oc-ttl{font-weight:900;font-size:15px;color:#111827;margin-bottom:4px}.oc-subt{font-size:13px;color:var(--oc-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.oc-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}
      .oc-pill{display:inline-flex;align-items:center;justify-content:center;padding:6px 10px;border-radius:999px;font-size:12px;font-weight:900;white-space:nowrap}.oc-pill.green{background:#ecfdf5;color:#047857}.oc-pill.orange{background:#fffbeb;color:#b45309}.oc-pill.red{background:#fef2f2;color:#b91c1c}.oc-pill.blue{background:#eff6ff;color:#2563eb}.oc-pill.gray{background:#f3f4f6;color:#374151}.oc-pill.purple{background:#f5f3ff;color:#6d28d9}
      .oc-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;padding:16px;}@media(max-width:1250px){.oc-cards{grid-template-columns:repeat(2,minmax(0,1fr));}}@media(max-width:800px){.oc-cards{grid-template-columns:1fr;}}
      .oc-card-item{border:1px solid var(--oc-border);border-radius:16px;padding:16px;background:#fff;box-shadow:var(--oc-shadow-sm);transition:var(--oc-transition)}.oc-card-item:hover{border-color:var(--oc-primary);box-shadow:var(--oc-shadow)}
      .oc-kanban{display:grid;grid-template-columns:repeat(5,minmax(250px,1fr));gap:14px;padding:16px;overflow:auto}.oc-kanban-col{background:#f9fafb;border:1px solid var(--oc-border);border-radius:16px;padding:12px;min-height:260px}.oc-kanban-title{font-weight:900;color:#111827;margin-bottom:10px;display:flex;justify-content:space-between}.oc-kanban-card{background:#fff;border:1px solid var(--oc-border);border-radius:12px;padding:12px;margin-bottom:10px;box-shadow:var(--oc-shadow-sm)}
      .oc-pagination{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin-top:18px;background:#fff;border:1px solid var(--oc-border);border-radius:14px;padding:14px 16px;box-shadow:var(--oc-shadow-sm)}
      .oc-empty{text-align:center;padding:45px;color:var(--oc-muted);background:#fff;border:1px dashed var(--oc-border);border-radius:16px;margin:16px;}
      .oc-loader{display:none;position:absolute;inset:0;background:rgba(255,255,255,.7);z-index:5;align-items:center;justify-content:center}.oc-loader.show{display:flex;}
      .oc-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.oc-form-grid.thirds{grid-template-columns:repeat(3,minmax(0,1fr));}@media(max-width:760px){.oc-form-grid,.oc-form-grid.thirds{grid-template-columns:1fr}}
      .oc-form-section{border:1px solid var(--oc-border);border-radius:14px;background:#fff;padding:14px;margin-bottom:14px}.oc-form-section-title{font-size:13px;font-weight:900;color:#111827;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px}.oc-label{display:block;font-size:13px;font-weight:800;color:#374151;margin-bottom:6px}.oc-field{width:100%;padding:10px 12px;border-radius:8px;border:1px solid var(--oc-border);background:#fff;font-size:14px;outline:none;transition:var(--oc-transition)}.oc-field:focus{border-color:var(--oc-primary);box-shadow:0 0 0 3px var(--oc-primary-light)}
      .oc-drawer{position:fixed;top:0;right:-760px;width:min(760px,96vw);height:100vh;background:#fff;z-index:1055;box-shadow:-20px 0 35px -20px rgba(15,23,42,.45);transition:right .24s ease;display:flex;flex-direction:column}.oc-drawer.open{right:0}.oc-drawer-h{padding:16px 18px;border-bottom:1px solid var(--oc-border);display:flex;align-items:center;justify-content:space-between;gap:12px;background:#fafafa}.oc-drawer-b{padding:16px;overflow-y:auto;flex:1}.oc-drawer-backdrop{display:none;position:fixed;inset:0;background:rgba(15,23,42,.45);z-index:1050}.oc-drawer-backdrop.open{display:block}.oc-mini-list{display:flex;flex-direction:column;gap:10px}.oc-mini-item{border:1px solid var(--oc-border);border-radius:14px;padding:12px;background:#fff;transition:var(--oc-transition)}.oc-mini-item:hover{border-color:var(--oc-primary);box-shadow:var(--oc-shadow-sm)}.oc-mini-item.active{border-color:var(--oc-primary);background:var(--oc-primary-light)}
      .oc-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px}.oc-tab{border:1px solid var(--oc-border);background:#fff;border-radius:999px;padding:9px 13px;font-weight:900;color:var(--oc-muted);cursor:pointer}.oc-tab.active{background:var(--oc-primary-light);border-color:var(--oc-primary);color:#4d7c0f}.oc-hide{display:none!important}
      .oc-toast-wrap{position:fixed;right:20px;bottom:20px;z-index:9999;display:flex;flex-direction:column;gap:10px}.oc-toast{min-width:280px;max-width:380px;background:#fff;border:1px solid var(--oc-border);border-radius:14px;box-shadow:var(--oc-shadow);padding:12px;display:flex;gap:10px;align-items:flex-start;animation:ocToastIn .25s ease forwards}@keyframes ocToastIn{from{transform:translateX(100%);opacity:0}to{transform:translateX(0);opacity:1}}
    </style>
@endsection

@section('content')
    <div class="app-content">
      <div class="content-overlay"></div><div class="header-navbar-shadow"></div>
      <div class="content-wrapper">
        <div class="oc-wrap">
          {{-- CI-Vereinheitlichung 2026-07-15 (Welle 2): Alt-Kopf durch das gemeinsame Bauteil ersetzt. --}}
          <x-page-head title="Maschinen &amp; Fahrzeuge"
              sub="Zentrale Verwaltung für Maschinen, Fahrzeuge, Service, TÜV, Abteilung, Ratenzahlung und Zahlungsanalyse."
              current="Maschinen &amp; Fahrzeuge" style="margin:0 0 14px;">
              <x-slot:actions>
                  <button type="button" class="oc-btn-soft" id="refreshMachinesBtn"><i data-lucide="refresh-cw"></i> Aktualisieren</button>
                  <button type="button" class="oc-btn" id="openMachineCreateBtn"><i data-lucide="plus"></i> Neue Maschine</button>
              </x-slot:actions>
          </x-page-head>

          <div class="oc-analytics" id="machineAnalytics">
            <div class="oc-stat"><div class="oc-stat-icon total"><i data-lucide="truck"></i></div><div><div class="oc-stat-label">Gesamt</div><div class="oc-stat-value" data-stat="total">0</div><div class="oc-stat-sub">Maschinen/Fahrzeuge</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon good"><i data-lucide="check-circle-2"></i></div><div><div class="oc-stat-label">Aktiv</div><div class="oc-stat-value" data-stat="active">0</div><div class="oc-stat-sub">Verfügbar</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon warn"><i data-lucide="wrench"></i></div><div><div class="oc-stat-label">Service</div><div class="oc-stat-value" data-stat="in_service">0</div><div class="oc-stat-sub">Im Service</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon bad"><i data-lucide="triangle-alert"></i></div><div><div class="oc-stat-label">Reparatur</div><div class="oc-stat-value" data-stat="repair">0</div><div class="oc-stat-sub">Defekt/Reparatur</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon warn"><i data-lucide="calendar-clock"></i></div><div><div class="oc-stat-label">TÜV</div><div class="oc-stat-value" data-stat="inspection_due">0</div><div class="oc-stat-sub">in 30 Tagen</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon gray"><i data-lucide="coins"></i></div><div><div class="oc-stat-label">Service/Jahr</div><div class="oc-stat-value" data-stat="service_cost_year">0 €</div><div class="oc-stat-sub">laufende Kosten</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon total"><i data-lucide="receipt"></i></div><div><div class="oc-stat-label">Raten Gesamt</div><div class="oc-stat-value" data-stat="installment_total">0 €</div><div class="oc-stat-sub">Finanzierung</div></div></div>
            <div class="oc-stat"><div class="oc-stat-icon good"><i data-lucide="wallet-cards"></i></div><div><div class="oc-stat-label">Raten Offen</div><div class="oc-stat-value" data-stat="installment_remaining">0 €</div><div class="oc-stat-sub">Restbetrag</div></div></div>
          </div>

          <div class="oc-toolbar">
            <div class="oc-toolbar-left">
              <div class="oc-filter-block search"><label class="oc-filter-label">Suche</label><input type="search" class="oc-input search" id="machineSearch" placeholder="Name, Modell, Besitzer, Kennzeichen..."></div>
              <div class="oc-filter-block"><label class="oc-filter-label">Branch</label><select class="oc-input oc-select" id="filterBranch"><option value="">Alle</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->branch }}</option>@endforeach</select></div>
              <div class="oc-filter-block"><label class="oc-filter-label">Abteilung</label><select class="oc-input oc-select" id="filterDepartment"><option value="">Alle</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->department_name }}</option>@endforeach</select></div>
              <div class="oc-filter-block"><label class="oc-filter-label">Status</label><select class="oc-input oc-select" id="filterStatus"><option value="">Alle</option>@foreach($machineStatuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
            </div>
            <div class="oc-toolbar-right">
              <div class="oc-filter-block" style="min-width:100px"><label class="oc-filter-label">Pro Seite</label><select class="oc-input" id="perPage"><option>12</option><option>24</option><option>48</option><option>100</option></select></div>
              <div class="d-flex" style="gap:6px"><button class="oc-btn-soft active" data-view="list" type="button"><i data-lucide="list"></i></button><button class="oc-btn-soft" data-view="card" type="button"><i data-lucide="layout-grid"></i></button><button class="oc-btn-soft" data-view="kanban" type="button"><i data-lucide="columns-3"></i></button></div>
            </div>
          </div>

          <div class="oc-card">
            <div class="oc-loader" id="machineLoader"><div class="spinner-border text-primary" role="status"></div></div>
            <div id="machineListView"><div class="oc-list-head"><div>ID</div><div>Maschine</div><div>Organisation</div><div>Kauf/Raten</div><div>Service</div><div>Status/TÜV</div><div class="text-right">Aktion</div></div><div class="oc-list" id="machineList"></div></div>
            <div id="machineCardView" class="oc-cards oc-hide"></div>
            <div id="machineKanbanView" class="oc-kanban oc-hide"></div>
          </div>
          <div class="oc-pagination"><div id="paginationInfo" class="text-muted"></div><div id="paginationButtons" class="d-flex" style="gap:6px"></div></div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="machineModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-xl modal-dialog-scrollable" role="document"><div class="modal-content">
        <form id="machineForm" enctype="multipart/form-data">@csrf<input type="hidden" name="id" id="machine_id">
          <div class="modal-header"><h5 class="modal-title" id="machineModalTitle">Neue Maschine</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div>
          <div class="modal-body">
            <div class="oc-form-section"><div class="oc-form-section-title">Stammdaten</div><div class="oc-form-grid thirds">
              <div><label class="oc-label">Name *</label><input class="oc-field" name="name" id="name" required></div>
              <div><label class="oc-label">Modell</label><input class="oc-field" name="model" id="model"></div>
              <div><label class="oc-label">Jahr</label><input type="number" class="oc-field" name="year" id="year"></div>
              <div><label class="oc-label">Farbe</label><input class="oc-field" name="color" id="color"></div>
              <div><label class="oc-label">Motortyp</label><input class="oc-field" name="engine_type" id="engine_type"></div>
              <div><label class="oc-label">Kilometerstand</label><input type="number" class="oc-field" name="mileage" id="mileage"></div>
              <div><label class="oc-label">Kennzeichen / Seriennummer</label><input class="oc-field" name="serial_no" id="serial_no"></div>
              <div><label class="oc-label">Besitzername</label><input class="oc-field" name="owner_name" id="owner_name"></div>
              <div><label class="oc-label">Besitzer Kontakt</label><input class="oc-field" name="owner_contact" id="owner_contact"></div>
            </div></div>
            <div class="oc-form-section"><div class="oc-form-section-title">Organisation</div><div class="oc-form-grid thirds">
              <div><label class="oc-label">Branch</label><select class="oc-field select2-machine" name="branch_id" id="branch_id"><option value="">Bitte wählen</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->branch }}</option>@endforeach</select></div>
              <div><label class="oc-label">Abteilung</label><select class="oc-field select2-machine" name="department_id" id="department_id"><option value="">Bitte wählen</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->department_name }}</option>@endforeach</select></div>
              <div><label class="oc-label">Artikelgruppe / Gewerk</label><select class="oc-field select2-machine" name="article_group" id="article_group"><option value="">Bitte wählen</option>@foreach($article_groups as $article)<option value="{{ $article->id }}">{{ $article->article_group }}</option>@endforeach</select></div>
              <div><label class="oc-label">Status</label><select class="oc-field" name="status" id="status">@foreach($machineStatuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
            </div></div>
            <div class="oc-form-section"><div class="oc-form-section-title">Kauf / Leasing</div><div class="oc-form-grid thirds">
              <div><label class="oc-label">Art des Kaufs *</label><select class="oc-field" name="purchase_type" id="purchase_type"><option value="Barzahlung">Barzahlung</option><option value="Ratenzahlung">Ratenzahlung</option><option value="Leasing">Leasing</option></select></div>
              <div class="purchase-fields"><label class="oc-label">Kaufpreis</label><input type="number" step="0.01" class="oc-field" name="purchase_price" id="purchase_price"></div>
              <div class="purchase-fields"><label class="oc-label">Kaufdatum</label><input type="date" class="oc-field" name="purchase_date" id="purchase_date"></div>
              <div class="leasing-fields oc-hide"><label class="oc-label">Leasing von</label><input class="oc-field" name="leasing_from" id="leasing_from"></div>
              <div class="leasing-fields oc-hide"><label class="oc-label">Leasing Start</label><input type="date" class="oc-field" name="leasing_start_date" id="leasing_start_date"></div>
              <div class="leasing-fields oc-hide"><label class="oc-label">Leasing Ende</label><input type="date" class="oc-field" name="leasing_end_date" id="leasing_end_date"></div>
              <div class="leasing-fields oc-hide"><label class="oc-label">Leasingpreis</label><input type="number" step="0.01" class="oc-field" name="leasing_price" id="leasing_price"></div>
            </div></div>
            <div class="oc-form-section"><div class="oc-form-section-title">Service / TÜV / Bild</div><div class="oc-form-grid thirds">
              <div><label class="oc-label">Letztes Servicedatum</label><input type="date" class="oc-field" name="last_service_date" id="last_service_date"></div>
              <div><label class="oc-label">TÜV aktiv</label><div class="custom-control custom-switch mt-1"><input type="checkbox" class="custom-control-input" id="technical_inspection" name="technical_inspection" value="1"><label class="custom-control-label" for="technical_inspection">Ja</label></div></div>
              <div id="tuvDateWrap"><label class="oc-label">TÜV Datum</label><input type="date" class="oc-field" name="technical_inspection_date" id="technical_inspection_date"></div>
              <div><label class="oc-label">Foto</label><input type="file" class="oc-field" name="image" id="image" accept="image/*"><div id="imagePreview" class="mt-1"></div></div>
              <div style="grid-column:span 2"><label class="oc-label">Beschreibung</label><textarea class="oc-field" rows="3" name="description" id="description"></textarea></div>
            </div></div>
          </div>
          <div class="modal-footer"><button type="button" class="oc-btn-soft" data-dismiss="modal">Schließen</button><button type="submit" class="oc-btn"><i data-lucide="save"></i> Speichern</button></div>
        </form>
      </div></div>
    </div>

    <div class="oc-drawer-backdrop" id="drawerBackdrop"></div>

    <div class="oc-drawer" id="serviceDrawer">
      <div class="oc-drawer-h"><div><strong id="serviceDrawerTitle">Service</strong><div class="text-muted small">Servicehistorie, Reparatur, TÜV und Kosten</div></div><button class="oc-btn-soft close-drawer" data-drawer="serviceDrawer" type="button"><i data-lucide="x"></i></button></div>
      <div class="oc-drawer-b">
        <form id="serviceForm" class="oc-form-section" enctype="multipart/form-data">@csrf<input type="hidden" name="id" id="service_id"><input type="hidden" name="machine_id" id="service_machine_id"><div class="oc-form-section-title d-flex justify-content-between"><span id="serviceFormTitle">Neuer Service</span><button class="oc-btn-soft" id="resetServiceFormBtn" type="button"><i data-lucide="plus"></i> Neu</button></div>
          <div class="oc-form-grid">
            <div><label class="oc-label">Serviceart</label><select class="oc-field" name="service_type" id="service_type"><option value="Repair">Reparatur</option><option value="TUV">TÜV</option><option value="Checkup">Inspektion</option><option value="Maintenance">Wartung</option></select></div>
            <div><label class="oc-label">Status</label><select class="oc-field" name="status" id="service_status">@foreach($serviceStatuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
            <div><label class="oc-label">Servicedatum</label><input type="date" class="oc-field" name="service_date" id="service_date"></div>
            <div><label class="oc-label">Dienstleister</label><select class="oc-field select2-service" name="service_by" id="service_by"><option value="">Bitte wählen</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ trim($employee->name . ' ' . $employee->lastname) }}</option>@endforeach</select></div>
            <div><label class="oc-label">Kosten</label><input type="number" step="0.01" class="oc-field" name="price" id="price"></div>
            <div><label class="oc-label">Kosten bezahlt von</label><select class="oc-field" name="paid_by" id="paid_by"><option value="">Bitte wählen</option><option value="Versicherung">Versicherung</option><option value="Mitarbeiter">Mitarbeiter</option><option value="Firma">Firma</option><option value="Andere">Andere</option></select></div>
            <div><label class="oc-label">Service Station</label><input class="oc-field" name="service_station" id="service_station"></div><div><label class="oc-label">Techniker</label><input class="oc-field" name="technician" id="technician"></div>
            <div><label class="oc-label">Standort</label><input class="oc-field" name="location" id="location"></div><div><label class="oc-label">Wartungsintervall Tage</label><input type="number" class="oc-field" name="maintenance_interval" id="maintenance_interval"></div>
            <div><label class="oc-label">E-Mail</label><input type="email" class="oc-field" name="email" id="email"></div><div><label class="oc-label">Telefon</label><input class="oc-field" name="phone" id="phone"></div>
            <div><label class="oc-label">Fehler entdeckt am</label><input type="date" class="oc-field" name="fault_detected_at" id="fault_detected_at"></div><div><label class="oc-label">Fehler entdeckt von</label><select class="oc-field select2-service" name="fault_detected_by" id="fault_detected_by"><option value="">Bitte wählen</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ trim($employee->name . ' ' . $employee->lastname) }}</option>@endforeach</select></div>
            <div style="grid-column:span 2"><label class="oc-label">Fehlerort</label><input class="oc-field" name="fault_detected_location" id="fault_detected_location"></div>
            <div style="grid-column:span 2"><label class="oc-label">Fehlerbeschreibung</label><textarea class="oc-field" rows="2" name="fault_description" id="fault_description"></textarea></div>
            <div style="grid-column:span 2"><label class="oc-label">Reparaturbeschreibung</label><textarea class="oc-field" rows="2" name="repair_description" id="repair_description"></textarea></div>
          </div><div class="mt-1"><button class="oc-btn" type="submit"><i data-lucide="save"></i> Service speichern</button></div>
        </form>
        <div class="oc-toolbar"><div class="oc-filter-block search"><label class="oc-filter-label">Service suchen</label><input class="oc-input search" id="serviceSearch"></div></div><div id="serviceList" class="oc-mini-list"></div><div class="oc-pagination"><div id="servicePaginationInfo" class="text-muted"></div><div id="servicePaginationButtons" class="d-flex" style="gap:6px"></div></div>
      </div>
    </div>

    <div class="oc-drawer" id="installmentDrawer">
      <div class="oc-drawer-h"><div><strong id="installmentDrawerTitle">Ratenzahlung</strong><div class="text-muted small">Finanzierung, Vertrag-PDF, Zahlungen und Restbetrag</div></div><button class="oc-btn-soft close-drawer" data-drawer="installmentDrawer" type="button"><i data-lucide="x"></i></button></div>
      <div class="oc-drawer-b">
        <div class="oc-analytics" style="grid-template-columns:repeat(3,minmax(0,1fr));">
          <div class="oc-stat"><div class="oc-stat-icon total"><i data-lucide="receipt"></i></div><div><div class="oc-stat-label">Gesamt</div><div class="oc-stat-value" data-installment-stat="total">0 €</div></div></div>
          <div class="oc-stat"><div class="oc-stat-icon good"><i data-lucide="wallet"></i></div><div><div class="oc-stat-label">Bezahlt</div><div class="oc-stat-value" data-installment-stat="paid">0 €</div></div></div>
          <div class="oc-stat"><div class="oc-stat-icon warn"><i data-lucide="hourglass"></i></div><div><div class="oc-stat-label">Offen</div><div class="oc-stat-value" data-installment-stat="remaining">0 €</div></div></div>
        </div>
        <div class="oc-tabs"><button type="button" class="oc-tab active" data-installment-tab="plans">Ratenpläne</button><button type="button" class="oc-tab" data-installment-tab="payments">Zahlungen</button></div>
        <div id="installmentPlansTab">
          <form id="installmentForm" class="oc-form-section" enctype="multipart/form-data">@csrf<input type="hidden" name="id" id="installment_form_id"><input type="hidden" name="asset_id" id="installment_asset_id"><input type="hidden" name="branch_id" id="installment_branch_id"><div class="oc-form-section-title d-flex justify-content-between"><span id="installmentFormTitle">Ratenzahlung anlegen</span><button class="oc-btn-soft" id="resetInstallmentFormBtn" type="button"><i data-lucide="plus"></i> Neu</button></div>
            <div class="oc-form-grid">
              <div><label class="oc-label">Ratenzahlungs-ID</label><input class="oc-field" name="installment_id" id="installment_id" required></div>
              <div><label class="oc-label">Gekauft bei</label><input class="oc-field" name="purchased_from" id="purchased_from"></div>
              <div><label class="oc-label">Preis pro Monat</label><input type="number" step="0.01" class="oc-field calc-installment" name="price_per_month" id="price_per_month" required></div>
              <div><label class="oc-label">Strafe/Rabatt</label><input type="number" step="0.01" class="oc-field calc-installment" name="fines" id="fines" value="0"></div>
              <div><label class="oc-label">Dauer Monate</label><input type="number" class="oc-field calc-installment" name="installment_duration" id="installment_duration" value="1" required></div>
              <div><label class="oc-label">Fälligkeitsdatum</label><input type="date" class="oc-field" name="due_date" id="due_date"></div>
              <div><label class="oc-label">Total</label><input type="number" step="0.01" class="oc-field" name="total" id="installment_total" required></div>
              <div><label class="oc-label">Bezahlt von</label><select class="oc-field select2-installment" name="paid_by" id="installment_paid_by"><option value="">Bitte wählen</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ trim($employee->name . ' ' . $employee->lastname) }}</option>@endforeach</select></div>
              <div><label class="oc-label">Bezahlverfahren</label><select class="oc-field" name="payment_method" id="installment_payment_method"><option value="Bank Transfer">Überweisung</option><option value="Cash">Bargeld</option><option value="Credit Card">Kreditkarte</option><option value="Debit Card">EC-Karte</option><option value="PayPal">PayPal</option><option value="Leasing">Leasing</option><option value="Installment">Ratenzahlung</option></select></div>
              <div><label class="oc-label">Status</label><select class="oc-field" name="status" id="installment_status">@foreach($installmentStatuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
              <div><label class="oc-label">Versicherer</label><input class="oc-field" name="insurance_provider" id="insurance_provider"></div><div><label class="oc-label">Versicherungsbetrag</label><input type="number" step="0.01" class="oc-field calc-installment" name="insurance_amount" id="insurance_amount" value="0"></div>
              <div><label class="oc-label">Versicherung Intervall</label><select class="oc-field calc-installment" name="insurance_payment_month" id="insurance_payment_month"><option value="">Ohne</option><option value="3 Monaten">3 Monaten</option><option value="6 Monaten">6 Monaten</option><option value="Jahr">Jahr</option></select></div><div><label class="oc-label">Versicherung Ablauf</label><input type="date" class="oc-field" name="insurance_expiry_date" id="insurance_expiry_date"></div>
              <div style="grid-column:span 2"><label class="oc-label">Vertrag PDF</label><input type="file" class="oc-field" name="contract_document" id="contract_document" accept="application/pdf"><div id="contractPreview" class="small mt-1"></div></div>
            </div><div class="mt-1"><button type="submit" class="oc-btn"><i data-lucide="save"></i> Ratenzahlung speichern</button></div>
          </form>
          <div class="oc-toolbar"><div class="oc-filter-block search"><label class="oc-filter-label">Raten suchen</label><input class="oc-input search" id="installmentSearch"></div></div>
          <div id="installmentList" class="oc-mini-list"></div><div class="oc-pagination"><div id="installmentPaginationInfo" class="text-muted"></div><div id="installmentPaginationButtons" class="d-flex" style="gap:6px"></div></div>
        </div>
        <div id="installmentPaymentsTab" class="oc-hide">
          <div class="oc-form-section"><div class="oc-form-section-title">Aktiver Ratenplan</div><div id="activeInstallmentInfo" class="text-muted">Bitte zuerst einen Ratenplan auswählen.</div></div>
          <form id="paymentForm" class="oc-form-section">@csrf<input type="hidden" name="id" id="payment_id"><input type="hidden" name="installment_id" id="payment_installment_id"><input type="hidden" name="branch_id" id="payment_branch_id"><div class="oc-form-section-title d-flex justify-content-between"><span id="paymentFormTitle">Zahlung erfassen</span><button class="oc-btn-soft" id="resetPaymentFormBtn" type="button"><i data-lucide="plus"></i> Neu</button></div>
            <div class="oc-form-grid">
              <div><label class="oc-label">Zahlungsbetrag</label><input type="number" step="0.01" class="oc-field calc-payment" name="payment_amount" id="payment_amount" required></div>
              <div><label class="oc-label">Zahlungsdatum</label><input type="date" class="oc-field" name="payment_date" id="payment_date" required></div>
              <div><label class="oc-label">Bezahlte Monate</label><input type="number" class="oc-field" name="paid_month_count" id="paid_month_count" value="1" required></div>
              <div><label class="oc-label">Verspätungsgebühr</label><input type="number" step="0.01" class="oc-field calc-payment" name="late_fee" id="late_fee" value="0"></div>
              <div><label class="oc-label">Restbetrag</label><input type="number" step="0.01" class="oc-field" name="payment_remained" id="payment_remained"></div>
              <div><label class="oc-label">Status</label><select class="oc-field" name="payment_status" id="payment_status"><option value="Bezahlt">Bezahlt</option><option value="Teilweise bezahlt">Teilweise bezahlt</option><option value="Verspätet">Verspätet</option></select></div>
              <div><label class="oc-label">Methode</label><select class="oc-field" name="payment_method" id="payment_method"><option value="Bank Transfer">Überweisung</option><option value="Cash">Bargeld</option><option value="Credit Card">Kreditkarte</option><option value="Debit Card">EC-Karte</option><option value="PayPal">PayPal</option></select></div>
              <div><label class="oc-label">Notiz</label><input class="oc-field" name="notes" id="notes"></div>
            </div><div class="mt-1"><button type="submit" class="oc-btn"><i data-lucide="save"></i> Zahlung speichern</button></div>
          </form>
          <div class="oc-toolbar"><div class="oc-filter-block search"><label class="oc-filter-label">Zahlungen suchen</label><input class="oc-input search" id="paymentSearch"></div></div><div id="paymentList" class="oc-mini-list"></div><div class="oc-pagination"><div id="paymentPaginationInfo" class="text-muted"></div><div id="paymentPaginationButtons" class="d-flex" style="gap:6px"></div></div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Datensatz löschen</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><p id="deleteText">Möchten Sie diesen Datensatz wirklich löschen?</p></div><div class="modal-footer"><button class="oc-btn-soft" data-dismiss="modal" type="button">Abbrechen</button><button class="oc-btn" id="confirmDeleteBtn" type="button" style="background:#ef4444">Ja, löschen</button></div></div></div></div>
    <div class="oc-toast-wrap" id="toastWrap"></div>
@endsection

@section('script')
    <script src="{{ asset('app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>
    <script src="https://unpkg.com/lucide@latest/dist/umd/lucide.min.js"></script>
    <script>
    (function(){
      const urls={
        machineData:@json(route('machine.inventory.data')), machineAnalytics:@json(route('machine.inventory.analytics')), machineStore:@json(route('machine.inventory.store')), machineUpdate:@json(route('machine.inventory.update')), machineShowTemplate:@json(url('/machine_show/__ID__')), machineDestroyTemplate:@json(url('/machine_destroy/__ID__')),
        serviceDataTemplate:@json(url('/machine_service_ajax/__ID__')), serviceShowTemplate:@json(url('/machine_service_show/__ID__')), serviceStore:@json(route('machine.service.store')), serviceUpdate:@json(route('machine.service.update')), serviceDestroyTemplate:@json(url('/machine_service_destroy/__ID__')),
        installmentDataTemplate:@json(url('/machine_installment_ajax/__ID__')), installmentShowTemplate:@json(url('/machine_installment_show/__ID__')), installmentStore:@json(route('machine.installment.store')), installmentUpdate:@json(route('machine.installment.update')), installmentDestroyTemplate:@json(url('/machine_installment_destroy/__ID__')),
        paymentDataTemplate:@json(url('/machine_installment_payment_ajax/__ID__')), paymentStore:@json(route('machine.installment.payment.store')), paymentUpdate:@json(route('machine.installment.payment.update')), paymentDestroyTemplate:@json(url('/machine_installment_payment_destroy/__ID__'))
      };
      const selectedMachineId=@json($selectedMachineId); const openServices=@json($openServices);
      const machineStatuses=@json($machineStatuses); let deleteAction=null; let timer=null; let state={page:1,view:'list',items:[],pagination:{}}; let serviceState={machineId:null,page:1,items:[],pagination:{}}; let installmentState={machine:null,page:1,items:[],pagination:{},active:null,paymentPage:1,payments:[],paymentPagination:{}};
      function csrf(){return $('meta[name="csrf-token"]').attr('content') || $('input[name="_token"]').first().val();} function urlTpl(t,id){return String(t).replace('__ID__',id);} function money(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));} function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#039;','"':'&quot;'}[c]));}
      function icons(){ if(window.lucide) lucide.createIcons(); } function toast(msg,bad=false){const icon=bad?'x-circle':'check-circle-2';const html=$(`<div class="oc-toast"><div class="oc-stat-icon ${bad?'bad':'good'}" style="width:34px;height:34px"><i data-lucide="${icon}"></i></div><div><strong>${bad?'Fehler':'Erfolg'}</strong><div class="small text-muted">${esc(msg)}</div></div><button class="oc-btn-ic" style="margin-left:auto" type="button">×</button></div>`);html.find('button').on('click',()=>html.remove());$('#toastWrap').append(html);icons();setTimeout(()=>html.fadeOut(200,()=>html.remove()),4200);} function ok(m){toast(m,false)} function bad(m){toast(m,true)}
      function pill(status,label){let c='gray'; if(['active','paid','completed','Bezahlt'].includes(status)) c='green'; if(['in_service','open','Teilweise bezahlt'].includes(status)) c='orange'; if(['repair','overdue','Verspätet'].includes(status)) c='red'; if(status==='inspection_due') c='purple'; return `<span class="oc-pill ${c}">${esc(label||status||'-')}</span>`;}
      function thumb(m){return m.image_url?`<img class="oc-thumb" src="${esc(m.image_url)}">`:`<div class="oc-avatar">${esc((m.name||'?').slice(0,2).toUpperCase())}</div>`;}
      function filters(){return{page:state.page,per_page:$('#perPage').val(),search:$('#machineSearch').val(),branch_id:$('#filterBranch').val(),department_id:$('#filterDepartment').val(),status:$('#filterStatus').val()};}
      function loadMachines(){ $('#machineLoader').addClass('show'); $.get(urls.machineData,filters()).done(r=>{state.items=r.items||[];state.pagination=r.pagination||{};renderMachines();renderPages();}).fail(x=>bad(x.responseJSON?.message||'Maschinen konnten nicht geladen werden.')).always(()=>$('#machineLoader').removeClass('show')); }
      function loadAnalytics(){ $.get(urls.machineAnalytics,filters()).done(r=>{Object.keys(r||{}).forEach(k=>{$(`[data-stat="${k}"]`).text(k.includes('cost')||k.includes('value')||k.includes('installment')?money(r[k]):r[k]);});}); }
      function row(m){return `<div class="oc-item"><div class="oc-item-row"><div><div class="oc-cell-title">ID</div><span class="oc-id-badge">#${m.id}</span></div><div class="oc-main">${thumb(m)}<div class="min-w-0"><div class="oc-ttl">${esc(m.display_name)}</div><div class="oc-subt">${esc(m.serial_no||'-')} · ${esc(m.year||'-')} · ${esc(m.color||'-')}</div><div class="small text-muted">${esc(m.owner_name||'-')} ${m.owner_contact?'· '+esc(m.owner_contact):''}</div></div></div><div><div class="oc-cell-title">Organisation</div><strong>${esc(m.branch||'-')}</strong><div class="small text-muted">${esc(m.department||'-')}</div><div class="small text-muted">${esc(m.article_group_name||'-')}</div></div><div><div class="oc-cell-title">Kauf/Raten</div><strong>${esc(m.purchase_type||'-')}</strong><div class="small text-muted">Kauf: ${money(m.purchase_price)}</div><div class="small text-muted">Offen: ${money(m.installments_remaining)}</div></div><div><div class="oc-cell-title">Service</div><strong>${m.services_count||0} Einträge</strong><div class="small text-muted">${money(m.services_total_cost)}</div><div class="small text-muted">${esc(m.latest_service_date||'-')}</div></div><div><div class="oc-cell-title">Status/TÜV</div>${pill(m.status,m.status_label)}<div class="small text-muted mt-1">TÜV: ${esc(m.technical_inspection_date||'-')}</div></div><div class="oc-actions"><button class="oc-btn-ic primary edit-machine" data-id="${m.id}" title="Bearbeiten"><i data-lucide="pencil"></i></button><button class="oc-btn-ic success service-machine" data-id="${m.id}" title="Service"><i data-lucide="wrench"></i></button><button class="oc-btn-ic warning installment-machine" data-id="${m.id}" title="Ratenzahlung"><i data-lucide="receipt"></i></button><button class="oc-btn-ic danger delete-machine" data-id="${m.id}" data-name="${esc(m.display_name)}" title="Löschen"><i data-lucide="trash-2"></i></button></div></div></div>`;}
      function card(m){return `<div class="oc-card-item"><div class="oc-main mb-1">${thumb(m)}<div><div class="oc-ttl">${esc(m.display_name)}</div><div class="oc-subt">${esc(m.branch||'-')} · ${esc(m.department||'-')}</div></div></div><div class="d-flex justify-content-between mb-1"><span>${pill(m.status,m.status_label)}</span><strong>${money(m.purchase_price)}</strong></div><div class="small text-muted mb-1">Service: ${m.services_count||0} · Raten offen: ${money(m.installments_remaining)}</div><div class="oc-actions justify-content-start"><button class="oc-btn-soft edit-machine" data-id="${m.id}"><i data-lucide="pencil"></i> Bearbeiten</button><button class="oc-btn-soft service-machine" data-id="${m.id}"><i data-lucide="wrench"></i></button><button class="oc-btn-soft installment-machine" data-id="${m.id}"><i data-lucide="receipt"></i></button></div></div>`;}
      function renderMachines(){ $('#machineListView,#machineCardView,#machineKanbanView').addClass('oc-hide'); if(state.view==='list'){ $('#machineListView').removeClass('oc-hide'); $('#machineList').html(state.items.map(row).join('')||'<div class="oc-empty">Keine Maschinen gefunden.</div>'); } if(state.view==='card'){ $('#machineCardView').removeClass('oc-hide').html(state.items.map(card).join('')||'<div class="oc-empty">Keine Maschinen gefunden.</div>'); } if(state.view==='kanban'){renderKanban();} icons(); }
      function renderKanban(){ $('#machineKanbanView').removeClass('oc-hide'); const cols=Object.keys(machineStatuses).map(k=>{const items=state.items.filter(x=>x.status===k);return `<div class="oc-kanban-col"><div class="oc-kanban-title"><span>${esc(machineStatuses[k])}</span><span>${items.length}</span></div>${items.map(m=>`<div class="oc-kanban-card"><strong>${esc(m.display_name)}</strong><div class="small text-muted">${esc(m.branch||'-')}</div><div class="small mt-1">Offen: ${money(m.installments_remaining)}</div><div class="mt-1"><button class="oc-btn-ic warning installment-machine" data-id="${m.id}"><i data-lucide="receipt"></i></button><button class="oc-btn-ic success service-machine" data-id="${m.id}"><i data-lucide="wrench"></i></button></div></div>`).join('')||'<div class="small text-muted">Keine Einträge</div>'}</div>`}).join(''); $('#machineKanbanView').html(cols); }
      function renderPages(){const p=state.pagination||{};$('#paginationInfo').text(p.total?`${p.from||0} - ${p.to||0} von ${p.total}`:'0 Einträge');let h=`<button class="oc-btn-soft page-btn" data-page="${Math.max((p.current_page||1)-1,1)}" ${(p.current_page||1)<=1?'disabled':''}>‹</button>`;h+=`<button class="oc-btn-soft page-btn" data-page="${Math.min((p.current_page||1)+1,p.last_page||1)}" ${(p.current_page||1)>=(p.last_page||1)?'disabled':''}>›</button>`;$('#paginationButtons').html(h);}
      function togglePurchase(){const v=$('#purchase_type').val();$('.leasing-fields').toggleClass('oc-hide',v!=='Leasing');$('.purchase-fields').toggleClass('oc-hide',v==='Leasing');}
      function resetMachine(){ $('#machineForm')[0].reset();$('#machine_id').val('');$('#status').val('active');$('.select2-machine').val('').trigger('change');$('#imagePreview').empty();$('#machineModalTitle').text('Neue Maschine');togglePurchase(); }
      function fillMachine(m){resetMachine();$('#machineModalTitle').text('Maschine bearbeiten');Object.keys(m).forEach(k=>{$('#'+k).val(m[k]);});$('#machine_id').val(m.id);$('#branch_id').val(m.branch_id).trigger('change');$('#department_id').val(m.department_id).trigger('change');$('#article_group').val(m.article_group).trigger('change');$('#technical_inspection').prop('checked',!!m.technical_inspection); if(m.image_url) $('#imagePreview').html(`<img src="${esc(m.image_url)}" style="width:80px;height:80px;object-fit:cover;border-radius:12px">`); togglePurchase(); $('#machineModal').modal('show'); }
      function submitMachine(e){e.preventDefault();let id=$('#machine_id').val();let fd=new FormData(this); if(id) fd.set('id',id); $.ajax({url:id?urls.machineUpdate:urls.machineStore,method:'POST',data:fd,processData:false,contentType:false,headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Gespeichert.');$('#machineModal').modal('hide');loadMachines();loadAnalytics();}).fail(x=>bad(x.status===422?Object.values(x.responseJSON.errors||{})[0]?.[0]:(x.responseJSON?.message||'Speichern fehlgeschlagen.')));}
      function confirmDel(text,cb){$('#deleteText').text(text);deleteAction=cb;$('#confirmDeleteModal').modal('show');}
      function delMachine(id,name){confirmDel(`Möchten Sie ${name} wirklich löschen?`,()=>{$.ajax({url:urlTpl(urls.machineDestroyTemplate,id),method:'DELETE',headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Gelöscht.');loadMachines();loadAnalytics();}).fail(x=>bad(x.responseJSON?.message||'Löschen fehlgeschlagen.'));});}
      function openDrawer(id){$('#drawerBackdrop').addClass('open');$('#'+id).addClass('open');icons();} function closeDrawer(id){$('#'+id).removeClass('open'); if(!$('.oc-drawer.open').length) $('#drawerBackdrop').removeClass('open');}
      function serviceFilters(){return{page:serviceState.page,per_page:8,search:$('#serviceSearch').val()};} function openService(machineId){serviceState.machineId=machineId;serviceState.page=1;$('#service_machine_id').val(machineId);let m=state.items.find(x=>Number(x.id)===Number(machineId));$('#serviceDrawerTitle').text(m?`Service: ${m.display_name}`:'Service');resetService(false);openDrawer('serviceDrawer');loadServices();}
      function resetService(keep=false){$('#serviceForm')[0].reset();$('#service_id').val(''); if(keep) $('#service_machine_id').val(serviceState.machineId); $('#service_status').val('open');$('.select2-service').val('').trigger('change');$('#serviceFormTitle').text('Neuer Service');}
      function loadServices(){if(!serviceState.machineId)return;$.get(urlTpl(urls.serviceDataTemplate,serviceState.machineId),serviceFilters()).done(r=>{serviceState.items=r.items||[];serviceState.pagination=r.pagination||{};renderServices();}).fail(x=>bad(x.responseJSON?.message||'Service konnte nicht geladen werden.'));}
      function renderServices(){const h=serviceState.items.map(s=>`<div class="oc-mini-item"><div class="d-flex justify-content-between"><div><strong>${esc(s.service_type)}</strong> ${pill(s.status,s.status_label)}<div class="small text-muted">${esc(s.service_date||'-')} · ${esc(s.service_employee||'-')}</div></div><div class="text-right"><strong>${money(s.price)}</strong><div class="mt-1"><button class="oc-btn-ic primary edit-service" data-id="${s.id}"><i data-lucide="pencil"></i></button><button class="oc-btn-ic danger delete-service" data-id="${s.id}"><i data-lucide="trash-2"></i></button></div></div></div><div class="small mt-1">${esc(s.service_station||'-')} · ${esc(s.technician||'-')}</div></div>`).join('');$('#serviceList').html(h||'<div class="oc-empty">Keine Serviceeinträge.</div>');const p=serviceState.pagination||{};$('#servicePaginationInfo').text(p.total?`${p.from||0} - ${p.to||0} von ${p.total}`:'0 Einträge');$('#servicePaginationButtons').html(`<button class="oc-btn-soft service-page" data-page="${Math.max((p.current_page||1)-1,1)}" ${(p.current_page||1)<=1?'disabled':''}>‹</button><button class="oc-btn-soft service-page" data-page="${Math.min((p.current_page||1)+1,p.last_page||1)}" ${(p.current_page||1)>=(p.last_page||1)?'disabled':''}>›</button>`);icons();}
      function fillService(s){resetService(true);Object.keys(s).forEach(k=>{$('#'+k).val(s[k]);});$('#service_id').val(s.id);$('#service_by').val(s.service_by).trigger('change');$('#fault_detected_by').val(s.fault_detected_by).trigger('change');$('#serviceFormTitle').text('Service bearbeiten');}
      function submitService(e){e.preventDefault();let id=$('#service_id').val();let fd=new FormData(this);if(id)fd.set('id',id);$.ajax({url:id?urls.serviceUpdate:urls.serviceStore,method:'POST',data:fd,processData:false,contentType:false,headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Service gespeichert.');resetService(true);loadServices();loadMachines();loadAnalytics();}).fail(x=>bad(x.status===422?Object.values(x.responseJSON.errors||{})[0]?.[0]:(x.responseJSON?.message||'Service speichern fehlgeschlagen.')));}
      function openInstallment(machineId){let m=state.items.find(x=>Number(x.id)===Number(machineId));installmentState.machine=m;installmentState.page=1;installmentState.active=null;$('#installmentDrawerTitle').text(m?`Ratenzahlung: ${m.display_name}`:'Ratenzahlung');$('#installment_asset_id').val(machineId);$('#installment_branch_id').val(m?.branch_id||'');$('#payment_branch_id').val(m?.branch_id||'');resetInstallment(false);resetPayment(false);openDrawer('installmentDrawer');loadInstallments();}
      function calcInstallment(){let pm=Number($('#price_per_month').val()||0),dur=Number($('#installment_duration').val()||1),ins=Number($('#insurance_amount').val()||0),fine=Number($('#fines').val()||0),freq=$('#insurance_payment_month').val();let mul=freq==='3 Monaten'?3:(freq==='6 Monaten'?6:(freq==='Jahr'?12:0));$('#installment_total').val(((pm*dur)+(ins*mul)-fine).toFixed(2));}
      function resetInstallment(keep=true){$('#installmentForm')[0].reset();$('#installment_form_id').val('');$('#installment_status').val('open');$('#contractPreview').empty();if(keep&&installmentState.machine){$('#installment_asset_id').val(installmentState.machine.id);$('#installment_branch_id').val(installmentState.machine.branch_id||'');}$('.select2-installment').val('').trigger('change');$('#installmentFormTitle').text('Ratenzahlung anlegen');}
      function loadInstallments(){if(!installmentState.machine)return;$.get(urlTpl(urls.installmentDataTemplate,installmentState.machine.id),{page:installmentState.page,per_page:8,search:$('#installmentSearch').val()}).done(r=>{installmentState.items=r.items||[];installmentState.pagination=r.pagination||{};renderInstallments();let s=r.summary||{};$('[data-installment-stat="total"]').text(money(s.total));$('[data-installment-stat="paid"]').text(money(s.paid));$('[data-installment-stat="remaining"]').text(money(s.remaining));}).fail(x=>bad(x.responseJSON?.message||'Raten konnten nicht geladen werden.'));}
      function renderInstallments(){let h=installmentState.items.map(i=>`<div class="oc-mini-item ${installmentState.active&&installmentState.active.id===i.id?'active':''}"><div class="d-flex justify-content-between"><div><strong>${esc(i.installment_id)}</strong> ${pill(i.status,i.status_label)}<div class="small text-muted">${esc(i.purchased_from||'-')} · fällig ${esc(i.due_date||'-')}</div></div><div class="text-right"><strong>${money(i.remaining_total)}</strong><div class="small text-muted">von ${money(i.total)}</div></div></div><div class="d-flex flex-wrap mt-1" style="gap:6px"><button class="oc-btn-soft select-installment" data-id="${i.id}" type="button"><i data-lucide="wallet-cards"></i> Zahlungen</button><button class="oc-btn-ic primary edit-installment" data-id="${i.id}" type="button"><i data-lucide="pencil"></i></button>${i.contract_url?`<a class="oc-btn-ic success" href="${esc(i.contract_url)}" target="_blank"><i data-lucide="book-open"></i></a>`:''}<button class="oc-btn-ic danger delete-installment" data-id="${i.id}" type="button"><i data-lucide="trash-2"></i></button></div></div>`).join('');$('#installmentList').html(h||'<div class="oc-empty">Keine Ratenzahlung vorhanden.</div>');let p=installmentState.pagination||{};$('#installmentPaginationInfo').text(p.total?`${p.from||0} - ${p.to||0} von ${p.total}`:'0 Einträge');$('#installmentPaginationButtons').html(`<button class="oc-btn-soft installment-page" data-page="${Math.max((p.current_page||1)-1,1)}" ${(p.current_page||1)<=1?'disabled':''}>‹</button><button class="oc-btn-soft installment-page" data-page="${Math.min((p.current_page||1)+1,p.last_page||1)}" ${(p.current_page||1)>=(p.last_page||1)?'disabled':''}>›</button>`);icons();}
      function fillInstallment(i){resetInstallment();Object.keys(i).forEach(k=>{$('#'+k).val(i[k]);});$('#installment_form_id').val(i.id);$('#installment_asset_id').val(i.asset_id);$('#installment_branch_id').val(i.branch_id||installmentState.machine?.branch_id||'');$('#installment_paid_by').val(i.paid_by).trigger('change');$('#installment_payment_method').val(i.payment_method||'Bank Transfer');$('#installment_total').val(i.total);$('#contractPreview').html(i.contract_url?`<a href="${esc(i.contract_url)}" target="_blank">Aktuellen Vertrag öffnen</a>`:'');$('#installmentFormTitle').text('Ratenzahlung bearbeiten');}
      function submitInstallment(e){e.preventDefault();let id=$('#installment_form_id').val();let fd=new FormData(this);if(id)fd.set('id',id);$.ajax({url:id?urls.installmentUpdate:urls.installmentStore,method:'POST',data:fd,processData:false,contentType:false,headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Ratenzahlung gespeichert.');resetInstallment();loadInstallments();loadMachines();loadAnalytics();}).fail(x=>bad(x.status===422?Object.values(x.responseJSON.errors||{})[0]?.[0]:(x.responseJSON?.message||'Ratenzahlung speichern fehlgeschlagen.')));}
      function activateInstallment(id){let i=installmentState.items.find(x=>Number(x.id)===Number(id));if(!i)return;installmentState.active=i;$('#payment_installment_id').val(i.id);$('#payment_branch_id').val(i.branch_id||installmentState.machine?.branch_id||'');$('#payment_amount').val(i.price_per_month||'');$('#payment_remained').val(i.remaining_total||'');$('#activeInstallmentInfo').html(`<strong>${esc(i.installment_id)}</strong> · Gesamt ${money(i.total)} · Bezahlt ${money(i.paid_total)} · Offen ${money(i.remaining_total)}`);switchInstallmentTab('payments');loadPayments();renderInstallments();}
      function switchInstallmentTab(tab){$('[data-installment-tab]').removeClass('active');$(`[data-installment-tab="${tab}"]`).addClass('active');$('#installmentPlansTab').toggleClass('oc-hide',tab!=='plans');$('#installmentPaymentsTab').toggleClass('oc-hide',tab!=='payments');}
      function resetPayment(clear=true){$('#paymentForm')[0].reset();$('#payment_id').val('');$('#paid_month_count').val(1);$('#late_fee').val(0);$('#payment_status').val('Bezahlt');if(!clear&&installmentState.active){$('#payment_installment_id').val(installmentState.active.id);$('#payment_branch_id').val(installmentState.active.branch_id||installmentState.machine?.branch_id||'');$('#payment_amount').val(installmentState.active.price_per_month||'');$('#payment_remained').val(installmentState.active.remaining_total||'');}$('#paymentFormTitle').text('Zahlung erfassen');}
      function loadPayments(){if(!installmentState.active)return;$.get(urlTpl(urls.paymentDataTemplate,installmentState.active.id),{page:installmentState.paymentPage,per_page:8,search:$('#paymentSearch').val()}).done(r=>{installmentState.payments=r.items||[];installmentState.paymentPagination=r.pagination||{};let s=r.summary||{};if(installmentState.active){installmentState.active.paid_total=s.paid;installmentState.active.remaining_total=s.remaining;}renderPayments();}).fail(x=>bad(x.responseJSON?.message||'Zahlungen konnten nicht geladen werden.'));}
      function renderPayments(){let h=installmentState.payments.map(p=>`<div class="oc-mini-item"><div class="d-flex justify-content-between"><div><strong>${money(p.payment_amount)}</strong> ${pill(p.payment_status,p.payment_status)}<div class="small text-muted">${esc(p.payment_date||'-')} · ${esc(p.payment_method||'-')} · ${p.paid_month_count} Monat(e)</div></div><div><button class="oc-btn-ic primary edit-payment" data-id="${p.id}"><i data-lucide="pencil"></i></button><button class="oc-btn-ic danger delete-payment" data-id="${p.id}"><i data-lucide="trash-2"></i></button></div></div>${p.notes?`<div class="small text-muted mt-1">${esc(p.notes)}</div>`:''}</div>`).join('');$('#paymentList').html(h||'<div class="oc-empty">Keine Zahlungen vorhanden.</div>');let p=installmentState.paymentPagination||{};$('#paymentPaginationInfo').text(p.total?`${p.from||0} - ${p.to||0} von ${p.total}`:'0 Einträge');$('#paymentPaginationButtons').html(`<button class="oc-btn-soft payment-page" data-page="${Math.max((p.current_page||1)-1,1)}" ${(p.current_page||1)<=1?'disabled':''}>‹</button><button class="oc-btn-soft payment-page" data-page="${Math.min((p.current_page||1)+1,p.last_page||1)}" ${(p.current_page||1)>=(p.last_page||1)?'disabled':''}>›</button>`);icons();}
      function submitPayment(e){e.preventDefault();if(!$('#payment_installment_id').val())return bad('Bitte zuerst einen Ratenplan auswählen.');let id=$('#payment_id').val();let data=$(this).serialize();$.ajax({url:id?urls.paymentUpdate:urls.paymentStore,method:'POST',data:data,headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Zahlung gespeichert.');resetPayment(false);loadPayments();loadInstallments();loadMachines();loadAnalytics();}).fail(x=>bad(x.status===422?Object.values(x.responseJSON.errors||{})[0]?.[0]:(x.responseJSON?.message||'Zahlung speichern fehlgeschlagen.')));}
      $(function(){ $('.oc-select').select2({width:'100%'});$('.select2-machine').select2({width:'100%',dropdownParent:$('#machineModal')});$('.select2-service').select2({width:'100%',dropdownParent:$('#serviceDrawer')});$('.select2-installment').select2({width:'100%',dropdownParent:$('#installmentDrawer')});
        $('#openMachineCreateBtn').on('click',()=>{resetMachine();$('#machineModal').modal('show')});$('#refreshMachinesBtn').on('click',()=>{loadMachines();loadAnalytics();});$('#machineForm').on('submit',submitMachine);$('#purchase_type').on('change',togglePurchase);
        $('#machineSearch,#serviceSearch,#installmentSearch,#paymentSearch').on('input',function(){clearTimeout(timer);timer=setTimeout(()=>{if(this.id==='machineSearch'){state.page=1;loadMachines();loadAnalytics();} if(this.id==='serviceSearch'){serviceState.page=1;loadServices();} if(this.id==='installmentSearch'){installmentState.page=1;loadInstallments();} if(this.id==='paymentSearch'){installmentState.paymentPage=1;loadPayments();}},260);});
        $('#filterBranch,#filterDepartment,#filterStatus,#perPage').on('change',()=>{state.page=1;loadMachines();loadAnalytics();});$(document).on('click','[data-view]',function(){state.view=$(this).data('view');$('[data-view]').removeClass('active');$(this).addClass('active');renderMachines();});$(document).on('click','.page-btn',function(){state.page=Number($(this).data('page'));loadMachines();});
        $(document).on('click','.edit-machine',function(){$.get(urlTpl(urls.machineShowTemplate,$(this).data('id'))).done(r=>fillMachine(r.item)).fail(()=>bad('Maschine konnte nicht geladen werden.'));});$(document).on('click','.delete-machine',function(){delMachine($(this).data('id'),$(this).data('name'));});$(document).on('click','.service-machine',function(){openService($(this).data('id'));});$(document).on('click','.installment-machine',function(){openInstallment($(this).data('id'));});
        $('.close-drawer').on('click',function(){closeDrawer($(this).data('drawer'));});$('#drawerBackdrop').on('click',()=>{$('.oc-drawer').removeClass('open');$('#drawerBackdrop').removeClass('open');});$('#confirmDeleteBtn').on('click',()=>{$('#confirmDeleteModal').modal('hide');if(deleteAction)deleteAction();});
        $('#serviceForm').on('submit',submitService);$('#resetServiceFormBtn').on('click',()=>resetService(true));$(document).on('click','.service-page',function(){serviceState.page=Number($(this).data('page'));loadServices();});$(document).on('click','.edit-service',function(){$.get(urlTpl(urls.serviceShowTemplate,$(this).data('id'))).done(r=>fillService(r.item)).fail(()=>bad('Service konnte nicht geladen werden.'));});$(document).on('click','.delete-service',function(){let id=$(this).data('id');confirmDel('Serviceeintrag wirklich löschen?',()=>{$.ajax({url:urlTpl(urls.serviceDestroyTemplate,id),method:'DELETE',headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Gelöscht.');loadServices();loadMachines();loadAnalytics();}).fail(x=>bad(x.responseJSON?.message||'Löschen fehlgeschlagen.'));});});
        $('#installmentForm').on('submit',submitInstallment);$('.calc-installment').on('input change',calcInstallment);$('#resetInstallmentFormBtn').on('click',()=>resetInstallment());$(document).on('click','.installment-page',function(){installmentState.page=Number($(this).data('page'));loadInstallments();});$(document).on('click','.edit-installment',function(){let i=installmentState.items.find(x=>Number(x.id)===Number($(this).data('id'))); if(i) fillInstallment(i);});$(document).on('click','.select-installment',function(){activateInstallment($(this).data('id'));});$(document).on('click','.delete-installment',function(){let id=$(this).data('id');confirmDel('Ratenzahlung wirklich löschen?',()=>{$.ajax({url:urlTpl(urls.installmentDestroyTemplate,id),method:'DELETE',headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Gelöscht.');loadInstallments();loadMachines();loadAnalytics();}).fail(x=>bad(x.responseJSON?.message||'Löschen fehlgeschlagen.'));});});$('[data-installment-tab]').on('click',function(){switchInstallmentTab($(this).data('installment-tab'));});
        $('#paymentForm').on('submit',submitPayment);$('#resetPaymentFormBtn').on('click',()=>resetPayment(false));$(document).on('click','.payment-page',function(){installmentState.paymentPage=Number($(this).data('page'));loadPayments();});$(document).on('click','.edit-payment',function(){let p=installmentState.payments.find(x=>Number(x.id)===Number($(this).data('id'))); if(!p)return;resetPayment(false);Object.keys(p).forEach(k=>$('#'+k).val(p[k]));$('#payment_id').val(p.id);$('#paymentFormTitle').text('Zahlung bearbeiten');});$(document).on('click','.delete-payment',function(){let id=$(this).data('id');confirmDel('Zahlung wirklich löschen?',()=>{$.ajax({url:urlTpl(urls.paymentDestroyTemplate,id),method:'DELETE',headers:{'X-CSRF-TOKEN':csrf()}}).done(r=>{ok(r.message||'Gelöscht.');loadPayments();loadInstallments();loadMachines();loadAnalytics();}).fail(x=>bad(x.responseJSON?.message||'Löschen fehlgeschlagen.'));});});
        @if(Session::has('save_msg')) ok(@json(session('save_msg'))); @endif @if(Session::has('updated_msg')) ok(@json(session('updated_msg'))); @endif @if(Session::has('delete_msg')) bad(@json(session('delete_msg'))); @endif
        togglePurchase();loadMachines();loadAnalytics();icons(); if(selectedMachineId&&openServices)setTimeout(()=>openService(selectedMachineId),400);
      });
    })();
    </script>
@endsection
