<option value="Klasse A" selected>Klasse A (Motorrad)</option>
<option value="Klasse A1">Klasse A1 (Leichtkrafträder)</option>
<option value="Klasse A2">Klasse A2 (Motorrad)</option>
<option value="Klasse B">Klasse B (Pkw)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger)</option>
<option value="Klasse C">Klasse C (Lkw)</option>
<option value="Klasse CE">Klasse CE (Lkw mit Anhänger)</option>
<option value="Klasse D">Klasse D (Bus)</option>
<option value="Klasse DE">Klasse DE (Bus mit Anhänger)</option>
<option value="Klasse T">Klasse T (Traktor)</option>
<option value="Klasse AM">Klasse AM (Moped, Mofa)</option>
<option value="Klasse L">Klasse L (Traktor)</option>
<option value="Klasse S">Klasse S (Selbstbalancierende Kraftfahrzeuge)</option>
<option value="Klasse M">Klasse M (Moped, Krafträder bis 50 cm³)</option>
<option value="Klasse C1">Klasse C1 (Kleintransporter bis 7,5 t)</option>
<option value="Klasse C1E">Klasse C1E (Kleintransporter bis 7,5 t mit Anhänger)</option>
<option value="Klasse D1">Klasse D1 (Kleinbusse bis 16 Personen)</option>
<option value="Klasse D1E">Klasse D1E (Kleinbusse bis 16 Personen mit Anhänger)</option>
<option value="Klasse AM">Klasse AM (Moped, Krafträder bis 50 cm³)</option>
<option value="Klasse L">Klasse L (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse F">Klasse F (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse G">Klasse G (Schlepper)</option>
<option value="Klasse B96">Klasse B96 (Pkw mit Anhänger über 750 kg, aber max. 3.500 kg)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger über 750 kg, max. 3.500 kg)</option>
<option value="Klasse L">Klasse L (Traktor)</option>
<option value="Klasse T">Klasse T (Traktor)</option>
<option value="Klasse M">Klasse M (Moped, Krafträder bis 50 cm³)</option>
<option value="Klasse S">Klasse S (Selbstbalancierende Kraftfahrzeuge)</option>
<option value="Klasse AM">Klasse AM (Moped, Mofa)</option>
<option value="Klasse C1">Klasse C1 (Kleintransporter bis 7,5 t)</option>
<option value="Klasse C1E">Klasse C1E (Kleintransporter bis 7,5 t mit Anhänger)</option>
<option value="Klasse D1">Klasse D1 (Kleinbusse bis 16 Personen)</option>
<option value="Klasse D1E">Klasse D1E (Kleinbusse bis 16 Personen mit Anhänger)</option>
<option value="Klasse F">Klasse F (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse G">Klasse G (Schlepper)</option>
<option value="Klasse B96">Klasse B96 (Pkw mit Anhänger über 750 kg, aber max. 3.500 kg)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger über 750 kg, max. 3.500 kg)</option>
<option value="Klasse L">Klasse L (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse F">Klasse F (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse G">Klasse G (Schlepper)</option>
<option value="Klasse B96">Klasse B96 (Pkw mit Anhänger über 750 kg, aber max. 3.500 kg)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger über 750 kg, max. 3.500 kg)</option>
<option value="Klasse AM">Klasse AM (Moped, Mofa)</option>
<option value="Klasse L">Klasse L (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse F">Klasse F (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse G">Klasse G (Schlepper)</option>
<option value="Klasse B96">Klasse B96 (Pkw mit Anhänger über 750 kg, aber max. 3.500 kg)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger über 750 kg, max. 3.500 kg)</option>
<option value="Klasse M">Klasse M (Moped, Krafträder bis 50 cm³)</option>
<option value="Klasse S">Klasse S (Selbstbalancierende Kraftfahrzeuge)</option>
<option value="Klasse T">Klasse T (Traktor)</option>
<option value="Klasse L">Klasse L (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse F">Klasse F (Land- oder Forstwirtschaftliche Zugmaschinen)</option>
<option value="Klasse G">Klasse G (Schlepper)</option>
<option value="Klasse B96">Klasse B96 (Pkw mit Anhänger über 750 kg, aber max. 3.500 kg)</option>
<option value="Klasse BE">Klasse BE (Pkw mit Anhänger über 750 kg, max. 3.500 kg)</option>
