<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HeatpumpChecklist extends Model
{
    use HasFactory;
    protected $fillable = [
        'customer_id',
        'construction_year',
        'persons_per_household',
        'total_living_area',
        'building_type_id',
        'two_separated_units',
        'construction_type',
        'wall_material',
        'wall_thickness',
        'heat_demand_per_m2',
        'constantly_heated_area',
        'number_of_bathrooms',
        'bathtub',
        'swimming_pool',
        'swimming_pool_size',
        'rain_shower',
        'rain_shower_size',
        'whirlpool',
        'whirlpool_size',
        'window_glazing',
        'planned_renovation',
        'window_replacement',
        'roof_insulation',
        'facade_insulation',
        'fireplace',
        'wood_consumption',
        'heating_manufacturer',
        'power_kw',
        'heating_medium',
        'heating_medium_value',
        'installation_location',
        'floor_number',
        'installed_pipes',
        'solar_system',
        'flat_collector',
        'tube_collector',
        'collector_area',
        'electricity_meter',
        'heat_pump_tariff',
        'storage_capacity_l',
        'hot_water_storage',
        'basement',
        'basement_electric_heating',
        'basement_heated_area',
        'ground_floor',
        'ground_floor_electric_heating',
        'ground_floor_heated_area',
        'upper_floor',
        'upper_floor_electric_heating',
        'upper_floor_heated_area',
        'attic',
        'attic_electric_heating',
        'attic_heated_area',
        'flush_heating_circuits',
        'heat_source',
        'cooling_function',
        'ventilation',
        'internet_connection',
        'internet_type',
        'underfloor_heating',
        'radiators',
        'room_height',
        'installation_suitable',
        'indoor_unit',
        'outdoor_unit',
        'crane_required',
        'entry_width1',
        'entry_height2',
        'entry_width3',
        'entry_height4',
        'new_heating_area',
        'new_heating_width',
        'new_heating_height',
        'connection_type',
        'connection_size',
    ];

}
