<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WPChecklist extends Model
{
    use HasFactory;

    protected $fillable = [
        'customer_id',
        'postcode',
        'wp_objective',
        'wp_object',
        'wp_heating_type',
        'construction_year',
        'living_space',
        'unusable_space',
        'number_people',
        'wp_number_we',
        'wp_number_stories',
        'glass1',
        'glass2',
        'glass3',
        'window_margin',
        'insulation_thickness',
        'wall_type',
        'wall_thickness',
        'wp_insulation_strength',
        'wp_insulation',
        'wp_rafter_strength',
        'wp_rafter',
        'wp_bathrooms',
        'wp_bathtub',
        'wp_bathtub_count',
        'wp_bathtub_measure',
        'wp_swimming_pool',
        'wp_swimming_pool_count',
        'solor',
        'number_collector',
        'chimney',
        'chimney_usage',
        'hlb_calc',
        'energy_first_year_consumption',
        'energy_second_year_consumption',
        'energy_third_year_consumption',
        'energy_consumption_type',
        'energy_total_year_consumption',
        'energy_avg_year_consumption',
        'energy_first_year_cost',
        'energy_second_year_cost',
        'energy_third_year_cost',
        'energy_total_year_cost',
        'energy_avg_year_cost',
        'heatpump',
        'exhibition_location',
        'exhibation_location_note',
        'heating_manufacture_year',
        'heating_type',
        'system_performance',
        'heating_company',
        'type_designation',
        'hot_water_preparation',
        'number_hotWaterConsumptionPerPerson',
        'general_heating_system',
        'pipe_system',
        'heating_circuit_distributor',
        'actuators',
        'suitable_cooling_system',
        'radiator',
        'thermostats',
        'thermostatic_valves',
        'radiator_cooling_system',
        'radiator_note',
        'meter_cabinet',
        'cabinet_size',
        'meter_cabinet_company',
        'ventilation',
        'ventilation_system',
        'ventilation_company',
        'ventilation_type',
        'heat_recovery',
    ];
}
